// ============================================================
//  CAUSATIVE FORM (THỂ SAI KHIẾN / 使役形 - SHIEKIKEI) — DATA
// ============================================================

export interface CausativeFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  causativeForm: string; // Dạng sai khiến hiragana (e.g. かわせる, たべさせる, させる, こさせる)
  causativeFormKanji: string; // Dạng sai khiến kanji (e.g. 買わせる, 食べさせる, させる, 来させる)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const CAUSATIVE_FORM_VERBS: CausativeFormVerb[] = [
  // ── NHÓM 1: Đổi âm cột い sang cột あ + せる (五段動詞) ──────
  // 1. Kết thúc い → わせる (⚠️ Đuôi い thành わ)
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    causativeForm: 'かわせる',
    causativeFormKanji: '買わせる',
    meaning: 'Bắt mua / Cho phép mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    causativeForm: 'うたわせる',
    causativeFormKanji: '歌わせる',
    meaning: 'Bắt hát / Cho hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    causativeForm: 'つかわせる',
    causativeFormKanji: '使わせる',
    meaning: 'Bắt dùng / Cho phép dùng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    causativeForm: 'はらわせる',
    causativeFormKanji: '払わせる',
    meaning: 'Bắt trả tiền',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    causativeForm: 'あわせる',
    causativeFormKanji: '会わせる',
    meaning: 'Cho phép gặp gỡ',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },
  {
    id: 'narau',
    kanji: '習います',
    hiragana: 'ならいます',
    causativeForm: 'ならわせる',
    causativeFormKanji: '習わせる',
    meaning: 'Cho học / Bắt học',
    hanViet: 'TẬP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_waseru',
  },

  // 2. Kết thúc き → かせる
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    causativeForm: 'かかせる',
    causativeFormKanji: '書かせる',
    meaning: 'Bắt viết / Cho viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kaseru',
  },
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    causativeForm: 'いかせる',
    causativeFormKanji: '行かせる',
    meaning: 'Bắt đi / Cho phép đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kaseru',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    causativeForm: 'きかせる',
    causativeFormKanji: '聞かせる',
    meaning: 'Cho nghe / Bắt nghe',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kaseru',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    causativeForm: 'はたらかせる',
    causativeFormKanji: '働かせる',
    meaning: 'Bắt làm việc / Cho làm',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kaseru',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    causativeForm: 'あるかせる',
    causativeFormKanji: '歩かせる',
    meaning: 'Bắt đi bộ',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kaseru',
  },

  // 3. Kết thúc ぎ → がせる
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    causativeForm: 'およがせる',
    causativeFormKanji: '泳がせる',
    meaning: 'Bắt bơi / Cho bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gaseru',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    causativeForm: 'いそがせる',
    causativeFormKanji: '急がせる',
    meaning: 'Bắt khẩn trương / Thúc giục',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gaseru',
  },
  {
    id: 'nugu',
    kanji: '脱ぎます',
    hiragana: 'ぬぎます',
    causativeForm: 'ぬがせる',
    causativeFormKanji: '脱がせる',
    meaning: 'Bắt cởi ra / Cởi giúp',
    hanViet: 'THOÁT',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gaseru',
  },

  // 4. Kết thúc し → させる
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    causativeForm: 'はなさせる',
    causativeFormKanji: '話させる',
    meaning: 'Bắt nói / Cho phép nói',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saseru1',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    causativeForm: 'ださせる',
    causativeFormKanji: '出させる',
    meaning: 'Bắt đưa ra / Bắt nộp',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saseru1',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    causativeForm: 'けさせる',
    causativeFormKanji: '消させる',
    meaning: 'Bắt tắt / Bắt xóa',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saseru1',
  },

  // 5. Kết thúc ち → たせる
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    causativeForm: 'またせる',
    causativeFormKanji: '待たせる',
    meaning: 'Bắt chờ đợi / Để ai đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_taseru',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    causativeForm: 'たたせる',
    causativeFormKanji: '立たせる',
    meaning: 'Bắt đứng dậy (phạt...)',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_taseru',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    causativeForm: 'もたせる',
    causativeFormKanji: '持たせる',
    meaning: 'Cho mang theo / Bắt cầm',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_taseru',
  },

  // 6. Kết thúc に → なせる
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    causativeForm: 'しなせる',
    causativeFormKanji: '死なせる',
    meaning: 'Làm chết / Để cho chết',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_naseru',
  },

  // 7. Kết thúc び → ばせる
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    causativeForm: 'あそばせる',
    causativeFormKanji: '遊ばせる',
    meaning: 'Cho phép vui chơi',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_baseru',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    causativeForm: 'よばせる',
    causativeFormKanji: '呼ばせる',
    meaning: 'Bắt gọi / Sai gọi đến',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_baseru',
  },
  {
    id: 'tobu',
    kanji: '飛びます',
    hiragana: 'とびます',
    causativeForm: 'とばせる',
    causativeFormKanji: '飛ばせる',
    meaning: 'Cho bay / Bắn đi',
    hanViet: 'PHI',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_baseru',
  },

  // 8. Kết thúc み → ませる
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    causativeForm: 'のませる',
    causativeFormKanji: '飲ませる',
    meaning: 'Cho uống / Bắt uống thuốc',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_maseru',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    causativeForm: 'よませる',
    causativeFormKanji: '読ませる',
    meaning: 'Bắt đọc / Cho đọc sách',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_maseru',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    causativeForm: 'やすませる',
    causativeFormKanji: '休ませる',
    meaning: 'Cho nghỉ ngơi',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_maseru',
  },
  {
    id: 'sumu',
    kanji: '住みます',
    hiragana: 'すみます',
    causativeForm: 'すませる',
    causativeFormKanji: '住ませる',
    meaning: 'Cho sinh sống',
    hanViet: 'TRÚ',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_maseru',
  },

  // 9. Kết thúc り → らせる
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    causativeForm: 'つくらせる',
    causativeFormKanji: '作らせる',
    meaning: 'Bắt làm / Sai nấu nướng',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_raseru',
  },
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    causativeForm: 'はしらせる',
    causativeFormKanji: '走らせる',
    meaning: 'Bắt chạy (phạt...)',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_raseru',
  },
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    causativeForm: 'かえらせる',
    causativeFormKanji: '帰らせる',
    meaning: 'Cho về / Bắt về',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_raseru',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    causativeForm: 'とらせる',
    causativeFormKanji: '取らせる',
    meaning: 'Sai lấy / Bắt lấy',
    hanViet: 'THỦ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_raseru',
  },
  {
    id: 'ganbaru',
    kanji: '頑張ります',
    hiragana: 'がんばります',
    causativeForm: 'がんばらせる',
    causativeFormKanji: '頑張らせる',
    meaning: 'Bắt phải cố gắng',
    hanViet: 'NGOAN TRƯƠNG',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_raseru',
  },

  // ── NHÓM 2: Bỏ ます → Thêm させる (一段動詞) ───────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    causativeForm: 'たべさせる',
    causativeFormKanji: '食べさせる',
    meaning: 'Cho ăn / Bắt ăn hết',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_saseru',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    causativeForm: 'みさせる',
    causativeFormKanji: '見させる',
    meaning: 'Cho xem / Bắt nhìn',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_saseru',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    causativeForm: 'おきさせる',
    causativeFormKanji: '起きさせる',
    meaning: 'Bắt thức dậy',
    hanViet: 'KHỞI',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_saseru',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    causativeForm: 'ねさせる',
    causativeFormKanji: '寝させる',
    meaning: 'Cho ngủ / Bắt đi ngủ',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_saseru',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    causativeForm: 'あけさせる',
    causativeFormKanji: '開けさせる',
    meaning: 'Bắt mở cửa',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_saseru',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    causativeForm: 'しめさせる',
    causativeFormKanji: '閉めさせる',
    meaning: 'Bắt đóng cửa',
    hanViet: 'BẾ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_saseru',
  },
  {
    id: 'oboeru',
    kanji: '覚えます',
    hiragana: 'おぼえます',
    causativeForm: 'おぼえさせる',
    causativeFormKanji: '覚えさせる',
    meaning: 'Bắt học thuộc lòng',
    hanViet: 'GIÁC',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_saseru',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    causativeForm: 'おしえさせる',
    causativeFormKanji: '教えさせる',
    meaning: 'Cho dạy / Bắt chỉ bảo',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_saseru',
  },
  {
    id: 'tomeru',
    kanji: '止めます',
    hiragana: 'とめます',
    causativeForm: 'とめさせる',
    causativeFormKanji: '止めさせる',
    meaning: 'Bắt dừng lại',
    hanViet: 'CHỈ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_saseru',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    causativeForm: 'させる',
    causativeFormKanji: 'させる',
    meaning: 'Bắt làm / Cho làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saseru',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    causativeForm: 'べんきょうさせる',
    causativeFormKanji: '勉強させる',
    meaning: 'Bắt học bài',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saseru',
  },
  {
    id: 'soujisuru',
    kanji: '掃除します',
    hiragana: 'そうじします',
    causativeForm: 'そうじさせる',
    causativeFormKanji: '掃除させる',
    meaning: 'Bắt dọn dẹp',
    hanViet: 'TẢO TRỪ',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saseru',
  },
  {
    id: 'untensuru',
    kanji: '運転します',
    hiragana: 'うんてんします',
    causativeForm: 'うんてんさせる',
    causativeFormKanji: '運転させる',
    meaning: 'Cho lái xe / Bắt lái xe',
    hanViet: 'VẬN CHUYỂN',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saseru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    causativeForm: 'こさせる',
    causativeFormKanji: '来させる',
    meaning: 'Bắt đến / Cho phép đến (⚠️ đọc là ko-sa-se-ru)',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru_kosaseru',
  },
];
