// ============================================================
//  CAUSATIVE-PASSIVE FORM (THỂ SAI KHIẾN BỊ ĐỘNG / 使役受身形) — DATA
// ============================================================

export interface CausativePassiveFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  causativePassiveForm: string; // Dạng sai khiến bị động hiragana (e.g. かわされる, たべさせられる, させられる, こさせられる)
  causativePassiveFormKanji: string; // Dạng sai khiến bị động kanji (e.g. 買わされる, 食べさせられる, させられる, 来させられる)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const CAUSATIVE_PASSIVE_FORM_VERBS: CausativePassiveFormVerb[] = [
  // ── NHÓM 1: Dạng rút gọn cột あ + される (五段動詞) ──────────
  // 1. Kết thúc い → わされる (⚠️ Đuôi い thành わ)
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    causativePassiveForm: 'かわされる',
    causativePassiveFormKanji: '買わされる',
    meaning: 'Bị ép mua / Bị bắt mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wasareru',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    causativePassiveForm: 'うたわされる',
    causativePassiveFormKanji: '歌わされる',
    meaning: 'Bị bắt hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wasareru',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    causativePassiveForm: 'はらわされる',
    causativePassiveFormKanji: '払わされる',
    meaning: 'Bị ép trả tiền',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wasareru',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    causativePassiveForm: 'つかわされる',
    causativePassiveFormKanji: '使わされる',
    meaning: 'Bị bắt sử dụng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wasareru',
  },
  {
    id: 'narau',
    kanji: '習います',
    hiragana: 'ならいます',
    causativePassiveForm: 'ならわされる',
    causativePassiveFormKanji: '習わされる',
    meaning: 'Bị ép học',
    hanViet: 'TẬP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wasareru',
  },

  // 2. Kết thúc き → かされる
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    causativePassiveForm: 'かかされる',
    causativePassiveFormKanji: '書かされる',
    meaning: 'Bị bắt viết (bản kiểm điểm...)',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kasareru',
  },
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    causativePassiveForm: 'いかされる',
    causativePassiveFormKanji: '行かされる',
    meaning: 'Bị bắt đi / Bị ép đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kasareru',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    causativePassiveForm: 'きかされる',
    causativePassiveFormKanji: '聞かされる',
    meaning: 'Bị bắt nghe (chuyện dài dòng...)',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kasareru',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    causativePassiveForm: 'はたらかされる',
    causativePassiveFormKanji: '働かされる',
    meaning: 'Bị bắt làm việc (tăng ca...)',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kasareru',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    causativePassiveForm: 'あるかされる',
    causativePassiveFormKanji: '歩かされる',
    meaning: 'Bị bắt đi bộ đường dài',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kasareru',
  },

  // 3. Kết thúc ぎ → がされる
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    causativePassiveForm: 'およがされる',
    causativePassiveFormKanji: '泳がされる',
    meaning: 'Bị bắt bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gasareru',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    causativePassiveForm: 'いそがされる',
    causativePassiveFormKanji: '急がされる',
    meaning: 'Bị thúc ép vội vàng',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gasareru',
  },

  // 4. Kết thúc し → させられる (⚠️ Đuôi し chỉ dùng dạng dài, KHÔNG rút gọn)
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    causativePassiveForm: 'はなさせられる',
    causativePassiveFormKanji: '話させられる',
    meaning: 'Bị bắt nói chuyện / Bắt khai',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saserareru',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    causativePassiveForm: 'ださせられる',
    causativePassiveFormKanji: '出させられる',
    meaning: 'Bị bắt đưa ra / nộp tiền',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saserareru',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    causativePassiveForm: 'けさせられる',
    causativePassiveFormKanji: '消させられる',
    meaning: 'Bị bắt xóa đi',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_saserareru',
  },

  // 5. Kết thúc ち → たされる
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    causativePassiveForm: 'またされる',
    causativePassiveFormKanji: '待たされる',
    meaning: 'Bị bắt chờ đợi lâu',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tasareru',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    causativePassiveForm: 'たたされる',
    causativePassiveFormKanji: '立たされる',
    meaning: 'Bị phạt đứng',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tasareru',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    causativePassiveForm: 'もたされる',
    causativePassiveFormKanji: '持たされる',
    meaning: 'Bị bắt xách đồ nặng',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tasareru',
  },

  // 6. Kết thúc に → なされる
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    causativePassiveForm: 'しなされる',
    causativePassiveFormKanji: '死なされる',
    meaning: 'Bị ép chết',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_nasareru',
  },

  // 7. Kết thúc び → ばされる
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    causativePassiveForm: 'よばされる',
    causativePassiveFormKanji: '呼ばされる',
    meaning: 'Bị bắt gọi đến',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_basareru',
  },
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    causativePassiveForm: 'あそばされる',
    causativePassiveFormKanji: '遊ばされる',
    meaning: 'Bị bắt chơi cùng',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_basareru',
  },

  // 8. Kết thúc み → まされる
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    causativePassiveForm: 'のまされる',
    causativePassiveFormKanji: '飲まされる',
    meaning: 'Bị ép uống rượu / thuốc đắng',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_masareru',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    causativePassiveForm: 'よまされる',
    causativePassiveFormKanji: '読まされる',
    meaning: 'Bị bắt đọc sách',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_masareru',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    causativePassiveForm: 'やすまされる',
    causativePassiveFormKanji: '休まされる',
    meaning: 'Bị bắt nghỉ việc',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_masareru',
  },

  // 9. Kết thúc り → らされる
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    causativePassiveForm: 'はしらされる',
    causativePassiveFormKanji: '走らされる',
    meaning: 'Bị bắt chạy bộ (phạt...)',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rasareru',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    causativePassiveForm: 'つくらされる',
    causativePassiveFormKanji: '作らされる',
    meaning: 'Bị bắt làm / nấu nướng',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rasareru',
  },
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    causativePassiveForm: 'かえらされる',
    causativePassiveFormKanji: '帰らされる',
    meaning: 'Bị bắt quay về',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rasareru',
  },
  {
    id: 'ganbaru',
    kanji: '頑張ります',
    hiragana: 'がんばります',
    causativePassiveForm: 'がんばらされる',
    causativePassiveFormKanji: '頑張らされる',
    meaning: 'Bị ép phải cố gắng',
    hanViet: 'NGOAN TRƯƠNG',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rasareru',
  },

  // ── NHÓM 2: Bỏ ます → Thêm させられる (一段動詞) ─────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    causativePassiveForm: 'たべさせられる',
    causativePassiveFormKanji: '食べさせられる',
    meaning: 'Bị bắt ăn (rau, ớt...)',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_saserareru',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    causativePassiveForm: 'みさせられる',
    causativePassiveFormKanji: '見させられる',
    meaning: 'Bị bắt xem',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_saserareru',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    causativePassiveForm: 'おきさせられる',
    causativePassiveFormKanji: '起きさせられる',
    meaning: 'Bị bắt dậy sớm',
    hanViet: 'KHỞI',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_saserareru',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    causativePassiveForm: 'ねさせられる',
    causativePassiveFormKanji: '寝させられる',
    meaning: 'Bị bắt đi ngủ',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_saserareru',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    causativePassiveForm: 'あけさせられる',
    causativePassiveFormKanji: '開けさせられる',
    meaning: 'Bị bắt mở',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_saserareru',
  },
  {
    id: 'oboeru',
    kanji: '覚えます',
    hiragana: 'おぼえます',
    causativePassiveForm: 'おぼえさせられる',
    causativePassiveFormKanji: '覚えさせられる',
    meaning: 'Bị bắt học thuộc lòng',
    hanViet: 'GIÁC',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_saserareru',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    causativePassiveForm: 'おしえさせられる',
    causativePassiveFormKanji: '教えさせられる',
    meaning: 'Bị bắt phải chỉ dạy',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_saserareru',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    causativePassiveForm: 'させられる',
    causativePassiveFormKanji: 'させられる',
    meaning: 'Bị bắt làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saserareru',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    causativePassiveForm: 'べんきょうさせられる',
    causativePassiveFormKanji: '勉強させられる',
    meaning: 'Bị bắt học bài',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saserareru',
  },
  {
    id: 'soujisuru',
    kanji: '掃除します',
    hiragana: 'そうじします',
    causativePassiveForm: 'そうじさせられる',
    causativePassiveFormKanji: '掃除させられる',
    meaning: 'Bị phạt dọn dẹp vệ sinh',
    hanViet: 'TẢO TRỪ',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saserareru',
  },
  {
    id: 'untensuru',
    kanji: '運転します',
    hiragana: 'うんてんします',
    causativePassiveForm: 'うんてんさせられる',
    causativePassiveFormKanji: '運転させられる',
    meaning: 'Bị bắt lái xe',
    hanViet: 'VẬN CHUYỂN',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_saserareru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    causativePassiveForm: 'こさせられる',
    causativePassiveFormKanji: '来させられる',
    meaning: 'Bị bắt đến (⚠️ đọc là ko-sa-se-ra-re-ru)',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru_kosaserareru',
  },
];
