// ============================================================
//  PASSIVE FORM (THỂ BỊ ĐỘNG / 受身形 - UKEMIKEI) — DATA
// ============================================================

export interface PassiveFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  passiveForm: string; // Dạng bị động hiragana (e.g. かわれる, たべられる, される, こられる)
  passiveFormKanji: string; // Dạng bị động kanji (e.g. 買われる, 食べられる, される, 来られる)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const PASSIVE_FORM_VERBS: PassiveFormVerb[] = [
  // ── NHÓM 1: Đổi âm cột い sang cột あ + れる (五段動詞) ──────
  // 1. Kết thúc い → われる (⚠️ Đuôi い thành わ)
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    passiveForm: 'かわれる',
    passiveFormKanji: '買われる',
    meaning: 'Bị / được mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },
  {
    id: 'sasou',
    kanji: '誘います',
    hiragana: 'さそいます',
    passiveForm: 'さそわれる',
    passiveFormKanji: '誘われる',
    meaning: 'Được rủ rê, mời mọc',
    hanViet: 'DỤ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },
  {
    id: 'warau',
    kanji: '笑います',
    hiragana: 'わらいます',
    passiveForm: 'わらわれる',
    passiveFormKanji: '笑われる',
    meaning: 'Bị cười nhạo',
    hanViet: 'TIẾU',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    passiveForm: 'あわれる',
    passiveFormKanji: '会われる',
    meaning: 'Được gặp',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    passiveForm: 'つかわれる',
    passiveFormKanji: '使われる',
    meaning: 'Được sử dụng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    passiveForm: 'うたわれる',
    passiveFormKanji: '歌われる',
    meaning: 'Được hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_wareru',
  },

  // 2. Kết thúc き → かれる
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    passiveForm: 'かかれる',
    passiveFormKanji: '書かれる',
    meaning: 'Được viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kareru',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    passiveForm: 'きかれる',
    passiveFormKanji: '聞かれる',
    meaning: 'Bị hỏi, được nghe',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kareru',
  },
  {
    id: 'tataku',
    kanji: '叩きます',
    hiragana: 'たたきます',
    passiveForm: 'たたかれる',
    passiveFormKanji: '叩かれる',
    meaning: 'Bị đánh, bị vỗ',
    hanViet: 'KHẤU',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kareru',
  },
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    passiveForm: 'いかれる',
    passiveFormKanji: '行かれる',
    meaning: 'Bị đi (bị động phiền toái)',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kareru',
  },
  {
    id: 'naku',
    kanji: '泣きます',
    hiragana: 'なきます',
    passiveForm: 'なかれる',
    passiveFormKanji: '泣かれる',
    meaning: 'Bị khóc (bị quấy rầy)',
    hanViet: 'KHỐC',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_kareru',
  },

  // 3. Kết thúc ぎ → がれる
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    passiveForm: 'およがれる',
    passiveFormKanji: '泳がれる',
    meaning: 'Được bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gareru',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    passiveForm: 'いそがれる',
    passiveFormKanji: '急がれる',
    meaning: 'Bị giục giã',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gareru',
  },

  // 4. Kết thúc し → される
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    passiveForm: 'はなされる',
    passiveFormKanji: '話される',
    meaning: 'Được nói chuyện',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_sareru',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    passiveForm: 'だされる',
    passiveFormKanji: '出される',
    meaning: 'Được đưa ra / nộp',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_sareru',
  },
  {
    id: 'sasu',
    kanji: '刺します',
    hiragana: 'さします',
    passiveForm: 'さされる',
    passiveFormKanji: '刺される',
    meaning: 'Bị chích / đâm (muỗi đốt...)',
    hanViet: 'THÍCH',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_sareru',
  },
  {
    id: 'korosu',
    kanji: '殺します',
    hiragana: 'ころします',
    passiveForm: 'ころされる',
    passiveFormKanji: '殺される',
    meaning: 'Bị giết',
    hanViet: 'SÁT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_sareru',
  },
  {
    id: 'damasu',
    kanji: '騙します',
    hiragana: 'だまします',
    passiveForm: 'だまされる',
    passiveFormKanji: '騙される',
    meaning: 'Bị lừa gạt',
    hanViet: 'PHIẾN',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_sareru',
  },

  // 5. Kết thúc ち → たれる
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    passiveForm: 'またれる',
    passiveFormKanji: '待たれる',
    meaning: 'Được chờ đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tareru',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    passiveForm: 'たたれる',
    passiveFormKanji: '立たれる',
    meaning: 'Bị đứng chắn trước mặt',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tareru',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    passiveForm: 'もたれる',
    passiveFormKanji: '持たれる',
    meaning: 'Được mang theo',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tareru',
  },

  // 6. Kết thúc に → なれる
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    passiveForm: 'しなれる',
    passiveFormKanji: '死なれる',
    meaning: 'Bị mất (người thân qua đời)',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_nareru',
  },

  // 7. Kết thúc び → ばれる
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    passiveForm: 'よばれる',
    passiveFormKanji: '呼ばれる',
    meaning: 'Được / bị gọi tên',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_barerua',
  },
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    passiveForm: 'あそばれる',
    passiveFormKanji: '遊ばれる',
    meaning: 'Bị trêu đùa',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_barerua',
  },

  // 8. Kết thúc み → まれる
  {
    id: 'fumu',
    kanji: '踏みます',
    hiragana: 'ふみます',
    passiveForm: 'ふまれる',
    passiveFormKanji: '踏まれる',
    meaning: 'Bị dẫm (lên chân...)',
    hanViet: 'ĐẠP',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },
  {
    id: 'tanomu',
    kanji: '頼みます',
    hiragana: 'たのみます',
    passiveForm: 'たのまれる',
    passiveFormKanji: '頼まれる',
    meaning: 'Được nhờ vả / yêu cầu',
    hanViet: 'LẠI',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },
  {
    id: 'nusumu',
    kanji: '盗みます',
    hiragana: 'ぬすみます',
    passiveForm: 'ぬすまれる',
    passiveFormKanji: '盗まれる',
    meaning: 'Bị trộm cắp',
    hanViet: 'ĐẠO',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },
  {
    id: 'kamu',
    kanji: '噛みます',
    hiragana: 'かみます',
    passiveForm: 'かまれる',
    passiveFormKanji: '噛まれる',
    meaning: 'Bị cắn (chó cắn...)',
    hanViet: 'GIẢO',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    passiveForm: 'のまれる',
    passiveFormKanji: '飲まれる',
    meaning: 'Bị uống mất',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    passiveForm: 'よまれる',
    passiveFormKanji: '読まれる',
    meaning: 'Được đọc',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mareru',
  },

  // 9. Kết thúc り → られる
  {
    id: 'shikaru',
    kanji: '叱ります',
    hiragana: 'しかります',
    passiveForm: 'しかられる',
    passiveFormKanji: '叱られる',
    meaning: 'Bị mắng, bị la',
    hanViet: 'SẤC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rareru1',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    passiveForm: 'とられる',
    passiveFormKanji: '取られる',
    meaning: 'Bị lấy mất / tước đoạt',
    hanViet: 'THỦ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rareru1',
  },
  {
    id: 'furu',
    kanji: '振ります',
    hiragana: 'ふります',
    passiveForm: 'ふられる',
    passiveFormKanji: '振られる',
    meaning: 'Bị từ chối / bị đá (tình cảm)',
    hanViet: 'CHẤN',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rareru1',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    passiveForm: 'つくられる',
    passiveFormKanji: '作られる',
    meaning: 'Được làm ra / sản xuất',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_rareru1',
  },

  // ── NHÓM 2: Bỏ ます → Thêm られる (一段動詞) ───────────────
  {
    id: 'homeru',
    kanji: '褒めます',
    hiragana: 'ほめます',
    passiveForm: 'ほめられる',
    passiveFormKanji: '褒められる',
    meaning: 'Được khen ngợi',
    hanViet: 'BAO',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_rareru',
  },
  {
    id: 'okoru',
    kanji: '怒られます',
    hiragana: 'おこられます',
    passiveForm: 'おこられる',
    passiveFormKanji: '怒られる',
    meaning: 'Bị tức giận / mắng mỏ',
    hanViet: 'NỘ',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_rareru',
  },
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    passiveForm: 'たべられる',
    passiveFormKanji: '食べられる',
    meaning: 'Bị ăn mất',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_rareru',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    passiveForm: 'みられる',
    passiveFormKanji: '見られる',
    meaning: 'Bị nhìn thấy',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_rareru',
  },
  {
    id: 'suteru',
    kanji: '捨てます',
    hiragana: 'すてます',
    passiveForm: 'すてられる',
    passiveFormKanji: '捨てられる',
    meaning: 'Bị vứt bỏ',
    hanViet: 'XẢ',
    group: 2,
    endingBefore: 'て',
    rule: 'g2_rareru',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    passiveForm: 'おしえられる',
    passiveFormKanji: '教えられる',
    meaning: 'Được chỉ dạy',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_rareru',
  },
  {
    id: 'ijimeru',
    kanji: '苛めます',
    hiragana: 'いじめます',
    passiveForm: 'いじめられる',
    passiveFormKanji: '苛められる',
    meaning: 'Bị bắt nạt',
    hanViet: 'HÀ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_rareru',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    passiveForm: 'される',
    passiveFormKanji: 'される',
    meaning: 'Bị / được làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_sareru',
  },
  {
    id: 'chuuisuru',
    kanji: '注意します',
    hiragana: 'ちゅういします',
    passiveForm: 'ちゅういされる',
    passiveFormKanji: '注意される',
    meaning: 'Bị nhắc nhở / cảnh báo',
    hanViet: 'CHÚ Ý',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_sareru',
  },
  {
    id: 'shoutaisuru',
    kanji: '招待します',
    hiragana: 'しょうたいします',
    passiveForm: 'しょうたいされる',
    passiveFormKanji: '招待される',
    meaning: 'Được mời / chiêu đãi',
    hanViet: 'CHIÊU ĐÃI',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_sareru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    passiveForm: 'こられる',
    passiveFormKanji: '来られる',
    meaning: 'Bị đến (làm phiền / 迷惑の受身)',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru_korareru',
  },
];
