// ============================================================
//  VOLITIONAL FORM (THỂ Ý CHÍ / THỂ よう / 意向形) — DATA
// ============================================================

export interface VolitionalFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  volitionalForm: string; // Dạng ý chí hiragana (e.g. いこう, たべよう)
  volitionalFormKanji: string; // Dạng ý chí kanji (e.g. 行こう, 食べよう)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

// ── Bàn phím Hiragana ảo ────────────────────────────────────────────
export const HIRAGANA_KEYBOARD_ROWS: string[][] = [
  ['あ', 'い', 'う', 'え', 'お'],
  ['か', 'き', 'く', 'け', 'こ'],
  ['さ', 'し', 'す', 'せ', 'そ'],
  ['た', 'ち', 'つ', 'て', 'と'],
  ['な', 'に', 'ぬ', 'ね', 'の'],
  ['は', 'ひ', 'ふ', 'へ', 'ほ'],
  ['ま', 'み', 'む', 'め', 'も'],
  ['や', '', 'ゆ', '', 'よ'],
  ['ら', 'り', 'る', 'れ', 'ろ'],
  ['わ', 'を', 'ん', 'っ', ''],
];

export const DAKUTEN_KEYBOARD_ROWS: string[][] = [
  ['が', 'ぎ', 'ぐ', 'げ', 'ご'],
  ['ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
  ['だ', 'ぢ', 'づ', 'で', 'ど'],
  ['ば', 'び', 'ぶ', 'べ', 'ぼ'],
  ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
];

export interface VolitionalFormRule {
  id: string;
  title: string;
  description: string;
  fromEnding: string;
  toEnding: string;
  group: 1 | 2 | 3;
  exampleFrom: string;
  exampleTo: string;
  exampleMeaning: string;
}

export const VOLITIONAL_FORM_RULES: VolitionalFormRule[] = [
  // ── Nhóm 1: Cột い → Cột お + う ───────────────────────────
  {
    id: 'g1_i_ou',
    title: 'Đuôi「い」→「おう」',
    description: 'Bỏ「ます」, chuyển âm「い」thành「おう」',
    fromEnding: 'い',
    toEnding: 'おう',
    group: 1,
    exampleFrom: 'かいます (買います)',
    exampleTo: 'かおう (買おう)',
    exampleMeaning: 'Mua / Cùng mua nào',
  },
  {
    id: 'g1_ki_kou',
    title: 'Đuôi「き」→「こう」',
    description: 'Bỏ「ます」, chuyển âm「き」thành「こう」',
    fromEnding: 'き',
    toEnding: 'こう',
    group: 1,
    exampleFrom: 'かきます (書きます)',
    exampleTo: 'かこう (書こう)',
    exampleMeaning: 'Viết / Cùng viết nào',
  },
  {
    id: 'g1_gi_gou',
    title: 'Đuôi「ぎ」→「ごう」',
    description: 'Bỏ「ます」, chuyển âm「ぎ」thành「ごう」',
    fromEnding: 'ぎ',
    toEnding: 'ごう',
    group: 1,
    exampleFrom: 'およぎます (泳ぎます)',
    exampleTo: 'およごう (泳ごう)',
    exampleMeaning: 'Bơi / Cùng bơi nào',
  },
  {
    id: 'g1_shi_sou',
    title: 'Đuôi「し」→「そう」',
    description: 'Bỏ「ます」, chuyển âm「し」thành「そう」',
    fromEnding: 'し',
    toEnding: 'そう',
    group: 1,
    exampleFrom: 'はなします (話します)',
    exampleTo: 'はなそう (話そう)',
    exampleMeaning: 'Nói chuyện / Cùng nói chuyện nào',
  },
  {
    id: 'g1_chi_tou',
    title: 'Đuôi「ち」→「とう」',
    description: 'Bỏ「ます」, chuyển âm「ち」thành「とう」',
    fromEnding: 'ち',
    toEnding: 'とう',
    group: 1,
    exampleFrom: 'たちます (立ちます)',
    exampleTo: 'たとう (立とう)',
    exampleMeaning: 'Đứng / Cùng đứng lên nào',
  },
  {
    id: 'g1_ni_nou',
    title: 'Đuôi「に」→「のう」',
    description: 'Bỏ「ます」, chuyển âm「に」thành「のう」',
    fromEnding: 'に',
    toEnding: 'のう',
    group: 1,
    exampleFrom: 'しにます (死にます)',
    exampleTo: 'しのう (死のう)',
    exampleMeaning: 'Chết',
  },
  {
    id: 'g1_bi_bou',
    title: 'Đuôi「び」→「ぼう」',
    description: 'Bỏ「ます」, chuyển âm「び」thành「ぼう」',
    fromEnding: 'び',
    toEnding: 'ぼう',
    group: 1,
    exampleFrom: 'あそびます (遊びます)',
    exampleTo: 'あそぼう (遊ぼう)',
    exampleMeaning: 'Chơi / Cùng chơi nào',
  },
  {
    id: 'g1_mi_mou',
    title: 'Đuôi「み」→「もう」',
    description: 'Bỏ「ます」, chuyển âm「み」thành「もう」',
    fromEnding: 'み',
    toEnding: 'もう',
    group: 1,
    exampleFrom: 'のみます (飲みます)',
    exampleTo: 'のもう (飲もう)',
    exampleMeaning: 'Uống / Cùng uống nào',
  },
  {
    id: 'g1_ri_rou',
    title: 'Đuôi「り」→「ろう」',
    description: 'Bỏ「ます」, chuyển âm「り」thành「ろう」',
    fromEnding: 'り',
    toEnding: 'ろう',
    group: 1,
    exampleFrom: 'かえります (帰ります)',
    exampleTo: 'かえろう (帰ろう)',
    exampleMeaning: 'Về / Cùng về nào',
  },

  // ── Nhóm 2: Bỏ ます + よう ─────────────────────────────────
  {
    id: 'g2_you',
    title: 'Nhóm 2: Bỏ「ます」+「よう」',
    description: 'Động từ Nhóm 2 chỉ cần bỏ「ます」và thêm「よう」',
    fromEnding: 'ます',
    toEnding: 'よう',
    group: 2,
    exampleFrom: 'たべます (食べます)',
    exampleTo: 'たべよう (食べよう)',
    exampleMeaning: 'Ăn / Cùng ăn nào',
  },

  // ── Nhóm 3: Bất quy tắc ───────────────────────────────────
  {
    id: 'g3_suru',
    title: 'Nhóm 3: します → しよう',
    description: 'Các động từ kết thúc bằng「します」đổi thành「しよう」',
    fromEnding: 'します',
    toEnding: 'しよう',
    group: 3,
    exampleFrom: 'べんきょうします (勉強します)',
    exampleTo: 'べんきょうしよう (勉強しよう)',
    exampleMeaning: 'Học / Cùng học nào',
  },
  {
    id: 'g3_kuru',
    title: 'Nhóm 3: きます (来ます) → こよう (来よう)',
    description: '⚠️ Động từ「来ます」đổi cách đọc từ「き」thành「こ」+「よう」',
    fromEnding: 'きます',
    toEnding: 'こよう',
    group: 3,
    exampleFrom: 'きます (来ます)',
    exampleTo: 'こよう (来よう)',
    exampleMeaning: 'Đến / Cùng đến nào',
  },
];

export const VOLITIONAL_FORM_VERBS: VolitionalFormVerb[] = [
  // ── NHÓM 1: い → おう ─────────────────────────────────────
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    volitionalForm: 'かおう',
    volitionalFormKanji: '買おう',
    meaning: 'Mua',
    hanViet: 'Mãi',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    volitionalForm: 'あおう',
    volitionalFormKanji: '会おう',
    meaning: 'Gặp gỡ',
    hanViet: 'Hội',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'iu',
    kanji: '言います',
    hiragana: 'いいます',
    volitionalForm: 'いおう',
    volitionalFormKanji: '言おう',
    meaning: 'Nói',
    hanViet: 'Ngôn',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'suu',
    kanji: '吸います',
    hiragana: 'すいます',
    volitionalForm: 'すおう',
    volitionalFormKanji: '吸おう',
    meaning: 'Hút (thuốc)',
    hanViet: 'Hấp',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    volitionalForm: 'つかおう',
    volitionalFormKanji: '使おう',
    meaning: 'Sử dụng',
    hanViet: 'Sử',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    volitionalForm: 'はらおう',
    volitionalFormKanji: '払おう',
    meaning: 'Trả tiền',
    hanViet: 'Phất',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    volitionalForm: 'うたおう',
    volitionalFormKanji: '歌おう',
    meaning: 'Hát',
    hanViet: 'Ca',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_ou',
  },

  // ── NHÓM 1: き → こう ─────────────────────────────────────
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    volitionalForm: 'かこう',
    volitionalFormKanji: '書こう',
    meaning: 'Viết',
    hanViet: 'Thư',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_kou',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    volitionalForm: 'きこう',
    volitionalFormKanji: '聞こう',
    meaning: 'Nghe / Hỏi',
    hanViet: 'Văn',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_kou',
  },
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    volitionalForm: 'いこう',
    volitionalFormKanji: '行こう',
    meaning: 'Đi',
    hanViet: 'Hành',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_kou',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    volitionalForm: 'はたらこう',
    volitionalFormKanji: '働こう',
    meaning: 'Làm việc',
    hanViet: 'Động',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_kou',
  },
  {
    id: 'ugoku',
    kanji: '動きます',
    hiragana: 'うごきます',
    volitionalForm: 'うごこう',
    volitionalFormKanji: '動こう',
    meaning: 'Chuyển động',
    hanViet: 'Động',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_kou',
  },

  // ── NHÓM 1: ぎ → ごう ─────────────────────────────────────
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    volitionalForm: 'およごう',
    volitionalFormKanji: '泳ごう',
    meaning: 'Bơi',
    hanViet: 'Vịnh',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gi_gou',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    volitionalForm: 'いすごう',
    volitionalFormKanji: '急ごう',
    meaning: 'Vội / Khẩn trương',
    hanViet: 'Cấp',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gi_gou',
  },

  // ── NHÓM 1: し → そう ─────────────────────────────────────
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    volitionalForm: 'はなそう',
    volitionalFormKanji: '話そう',
    meaning: 'Nói chuyện',
    hanViet: 'Thoại',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_sou',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    volitionalForm: 'だそう',
    volitionalFormKanji: '出そう',
    meaning: 'Lấy ra / Gửi nộp',
    hanViet: 'Xuất',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_sou',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    volitionalForm: 'けそう',
    volitionalFormKanji: '消そう',
    meaning: 'Tắt / Xóa',
    hanViet: 'Tiêu',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_sou',
  },
  {
    id: 'naosu',
    kanji: '直します',
    hiragana: 'なおします',
    volitionalForm: 'なおそう',
    volitionalFormKanji: '直そう',
    meaning: 'Sửa chữa',
    hanViet: 'Trực',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_sou',
  },

  // ── NHÓM 1: ち → とう ─────────────────────────────────────
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    volitionalForm: 'たとう',
    volitionalFormKanji: '立とう',
    meaning: 'Đứng',
    hanViet: 'Lập',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_tou',
  },
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    volitionalForm: 'まとう',
    volitionalFormKanji: '待とう',
    meaning: 'Chờ đợi',
    hanViet: 'Đãi',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_tou',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    volitionalForm: 'もとう',
    volitionalFormKanji: '持とう',
    meaning: 'Cầm / Mang',
    hanViet: 'Trì',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_tou',
  },

  // ── NHÓM 1: に → のう ─────────────────────────────────────
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    volitionalForm: 'しのう',
    volitionalFormKanji: '死のう',
    meaning: 'Chết',
    hanViet: 'Tử',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_ni_nou',
  },

  // ── NHÓM 1: び → ぼう ─────────────────────────────────────
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    volitionalForm: 'あそぼう',
    volitionalFormKanji: '遊ぼう',
    meaning: 'Chơi',
    hanViet: 'Du',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_bou',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    volitionalForm: 'よぼう',
    volitionalFormKanji: '呼ぼう',
    meaning: 'Gọi',
    hanViet: 'Hô',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_bou',
  },
  {
    id: 'erabu',
    kanji: '選びます',
    hiragana: 'えらびます',
    volitionalForm: 'えらぼう',
    volitionalFormKanji: '選ぼう',
    meaning: 'Chọn lựa',
    hanViet: 'Tuyển',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_bou',
  },

  // ── NHÓM 1: み → もう ─────────────────────────────────────
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    volitionalForm: 'のもう',
    volitionalFormKanji: '飲もう',
    meaning: 'Uống',
    hanViet: 'Ẩm',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_mou',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    volitionalForm: 'やすもう',
    volitionalFormKanji: '休もう',
    meaning: 'Nghỉ ngơi',
    hanViet: 'Hưu',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_mou',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    volitionalForm: 'よもう',
    volitionalFormKanji: '読もう',
    meaning: 'Đọc',
    hanViet: 'Độc',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_mou',
  },
  {
    id: 'sumu',
    kanji: '住みます',
    hiragana: 'すみます',
    volitionalForm: 'すもう',
    volitionalFormKanji: '住もう',
    meaning: 'Sinh sống',
    hanViet: 'Trú',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_mou',
  },

  // ── NHÓM 1: り → ろう ─────────────────────────────────────
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    volitionalForm: 'かえろう',
    volitionalFormKanji: '帰ろう',
    meaning: 'Về nhà',
    hanViet: 'Quy',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_rou',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    volitionalForm: 'とろう',
    volitionalFormKanji: '取ろう',
    meaning: 'Lấy',
    hanViet: 'Thủ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_rou',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    volitionalForm: 'つくろう',
    volitionalFormKanji: '作ろう',
    meaning: 'Chế tạo / Làm',
    hanViet: 'Tác',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_rou',
  },
  {
    id: 'ganbaru',
    kanji: '頑張ります',
    hiragana: 'がんばります',
    volitionalForm: 'がんばろう',
    volitionalFormKanji: '頑張ろう',
    meaning: 'Cố gắng',
    hanViet: 'Ngoan Trương',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_rou',
  },
  {
    id: 'hairu',
    kanji: '入ります',
    hiragana: 'はいります',
    volitionalForm: 'はいろう',
    volitionalFormKanji: '入ろう',
    meaning: 'Đi vào',
    hanViet: 'Nhập',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_rou',
  },

  // ── NHÓM 2: Bỏ ます + よう ─────────────────────────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    volitionalForm: 'たべよう',
    volitionalFormKanji: '食べよう',
    meaning: 'Ăn',
    hanViet: 'Thực',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_you',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    volitionalForm: 'みよう',
    volitionalFormKanji: '見よう',
    meaning: 'Xem / Nhìn',
    hanViet: 'Kiến',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_you',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    volitionalForm: 'ねよう',
    volitionalFormKanji: '寝よう',
    meaning: 'Ngủ',
    hanViet: 'Tẩm',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_you',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    volitionalForm: 'おきよう',
    volitionalFormKanji: '起きよう',
    meaning: 'Thức dậy',
    hanViet: 'Khởi',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_you',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    volitionalForm: 'あけよう',
    volitionalFormKanji: '開けよう',
    meaning: 'Mở (cửa)',
    hanViet: 'Khai',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_you',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    volitionalForm: 'しめよう',
    volitionalFormKanji: '閉めよう',
    meaning: 'Đóng (cửa)',
    hanViet: 'Bế',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_you',
  },
  {
    id: 'hajimeru',
    kanji: '始めます',
    hiragana: 'はじめます',
    volitionalForm: 'はじめよう',
    volitionalFormKanji: '始めよう',
    meaning: 'Bắt đầu',
    hanViet: 'Thủy',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_you',
  },
  {
    id: 'yameru',
    kanji: 'やめます',
    hiragana: 'やめます',
    volitionalForm: 'やめよう',
    volitionalFormKanji: 'やめよう',
    meaning: 'Từ bỏ / Nghỉ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_you',
  },
  {
    id: 'oboeru',
    kanji: '覚えます',
    hiragana: 'おぼえます',
    volitionalForm: 'おぼえよう',
    volitionalFormKanji: '覚えよう',
    meaning: 'Ghi nhớ',
    hanViet: 'Giác',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_you',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    volitionalForm: 'おしえよう',
    volitionalFormKanji: '教えよう',
    meaning: 'Dạy / Chỉ bảo',
    hanViet: 'Giáo',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_you',
  },

  // ── NHÓM 3: Bất quy tắc ───────────────────────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    volitionalForm: 'しよう',
    volitionalFormKanji: 'しよう',
    meaning: 'Làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'benkyou_suru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    volitionalForm: 'べんきょうしよう',
    volitionalFormKanji: '勉強しよう',
    meaning: 'Học tập',
    hanViet: 'Miễn Cưỡng',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'sanpo_suru',
    kanji: '散歩します',
    hiragana: 'さんぽします',
    volitionalForm: 'さんぽしよう',
    volitionalFormKanji: '散歩しよう',
    meaning: 'Đi dạo',
    hanViet: 'Tản Bộ',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'kaimono_suru',
    kanji: '買い物します',
    hiragana: 'かいものします',
    volitionalForm: 'かいものしよう',
    volitionalFormKanji: '買い物しよう',
    meaning: 'Mua sắm',
    hanViet: 'Mãi Vật',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'ryokou_suru',
    kanji: '旅行します',
    hiragana: 'りょこうします',
    volitionalForm: 'りょこうしよう',
    volitionalFormKanji: '旅行しよう',
    meaning: 'Đi du lịch',
    hanViet: 'Lữ Hành',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    volitionalForm: 'こよう',
    volitionalFormKanji: '来よう',
    meaning: 'Đến',
    hanViet: 'Lai',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru',
  },
];
