export interface KanjiN5Example {
  word: string;
  reading: string;
  meaning: string;
}

export interface KanjiN5Item {
  id: string;
  kanji: string;
  hanViet: string;
  meaning: string;
  onyomi: string;
  kunyomi: string;
  strokes: number;
  icon: string;
  tone: 'sun' | 'ink' | 'leaf' | 'water' | 'gold' | 'rose' | 'sky' | 'stone';
  mnemonic: string;
  examples: KanjiN5Example[];
}

export interface KanjiN5Lesson {
  slug: string;
  number: number;
  title: string;
  japaneseTitle: string;
  theme: string;
  summary: string;
  focus: string;
  items: KanjiN5Item[];
}

const KANJI_N5_SOURCE_LESSONS: KanjiN5Lesson[] = [
  {
    slug: 'bai-1',
    number: 1,
    title: 'Số, người và Nhật Bản',
    japaneseTitle: '数字・人・日本',
    theme: '日・人・年',
    summary: 'Làm quen với những chữ xuất hiện dày đặc trong lịch, quốc tịch và câu giới thiệu.',
    focus: 'Nhìn mặt chữ thật nhanh trước khi học ví dụ ghép từ.',
    items: [
      {
        id: 'nichi',
        kanji: '日',
        hanViet: 'Nhật',
        meaning: 'ngày, mặt trời, Nhật Bản',
        onyomi: 'ニチ、ジツ',
        kunyomi: 'ひ、び、か',
        strokes: 4,
        icon: 'fas fa-sun',
        tone: 'sun',
        mnemonic: 'Hình mặt trời được vẽ gọn lại thành một ô sáng.',
        examples: [
          { word: '日本', reading: 'にほん', meaning: 'Nhật Bản' },
          { word: '日曜日', reading: 'にちようび', meaning: 'chủ nhật' },
        ],
      },
      {
        id: 'ichi',
        kanji: '一',
        hanViet: 'Nhất',
        meaning: 'một',
        onyomi: 'イチ',
        kunyomi: 'ひと',
        strokes: 1,
        icon: 'fas fa-minus',
        tone: 'ink',
        mnemonic: 'Một nét ngang duy nhất, dễ nhận ra nhất trong Kanji.',
        examples: [
          { word: '一つ', reading: 'ひとつ', meaning: 'một cái' },
          { word: '一人', reading: 'ひとり', meaning: 'một người' },
        ],
      },
      {
        id: 'kuni',
        kanji: '国',
        hanViet: 'Quốc',
        meaning: 'đất nước',
        onyomi: 'コク',
        kunyomi: 'くに',
        strokes: 8,
        icon: 'fas fa-flag',
        tone: 'rose',
        mnemonic: 'Một vùng đất được bao quanh bởi đường biên.',
        examples: [
          { word: '国', reading: 'くに', meaning: 'đất nước' },
          { word: '外国', reading: 'がいこく', meaning: 'nước ngoài' },
        ],
      },
      {
        id: 'hito',
        kanji: '人',
        hanViet: 'Nhân',
        meaning: 'người',
        onyomi: 'ジン、ニン',
        kunyomi: 'ひと',
        strokes: 2,
        icon: 'fas fa-user',
        tone: 'sky',
        mnemonic: 'Hai nét như dáng một người đang đứng.',
        examples: [
          { word: '人', reading: 'ひと', meaning: 'người' },
          { word: '日本人', reading: 'にほんじん', meaning: 'người Nhật' },
        ],
      },
      {
        id: 'toshi',
        kanji: '年',
        hanViet: 'Niên',
        meaning: 'năm, tuổi',
        onyomi: 'ネン',
        kunyomi: 'とし',
        strokes: 6,
        icon: 'fas fa-calendar-days',
        tone: 'gold',
        mnemonic: 'Nhớ như một bó lịch được đánh dấu theo từng năm.',
        examples: [
          { word: '今年', reading: 'ことし', meaning: 'năm nay' },
          { word: '一年', reading: 'いちねん', meaning: 'một năm' },
        ],
      },
      {
        id: 'ookii',
        kanji: '大',
        hanViet: 'Đại',
        meaning: 'to, lớn',
        onyomi: 'ダイ、タイ',
        kunyomi: 'おお',
        strokes: 3,
        icon: 'fas fa-up-right-and-down-left-from-center',
        tone: 'stone',
        mnemonic: 'Dáng người dang tay ra thật rộng để chỉ cái lớn.',
        examples: [
          { word: '大学', reading: 'だいがく', meaning: 'đại học' },
          { word: '大きい', reading: 'おおきい', meaning: 'to, lớn' },
        ],
      },
      {
        id: 'juu',
        kanji: '十',
        hanViet: 'Thập',
        meaning: 'mười',
        onyomi: 'ジュウ',
        kunyomi: 'とお',
        strokes: 2,
        icon: 'fas fa-plus',
        tone: 'ink',
        mnemonic: 'Hai nét giao nhau như mốc đếm tròn 10.',
        examples: [
          { word: '十', reading: 'じゅう', meaning: 'mười' },
          { word: '十日', reading: 'とおか', meaning: 'ngày mùng 10' },
        ],
      },
      {
        id: 'ni',
        kanji: '二',
        hanViet: 'Nhị',
        meaning: 'hai',
        onyomi: 'ニ',
        kunyomi: 'ふた',
        strokes: 2,
        icon: 'fas fa-grip-lines',
        tone: 'ink',
        mnemonic: 'Hai nét ngang xếp chồng, nhìn là nhớ số hai.',
        examples: [
          { word: '二つ', reading: 'ふたつ', meaning: 'hai cái' },
          { word: '二人', reading: 'ふたり', meaning: 'hai người' },
        ],
      },
      {
        id: 'hon',
        kanji: '本',
        hanViet: 'Bản',
        meaning: 'sách, gốc, bản',
        onyomi: 'ホン',
        kunyomi: 'もと',
        strokes: 5,
        icon: 'fas fa-book',
        tone: 'leaf',
        mnemonic: 'Chữ 木 thêm một nét ở gốc, từ gốc cây mở rộng thành bản gốc.',
        examples: [
          { word: '本', reading: 'ほん', meaning: 'sách' },
          { word: '日本', reading: 'にほん', meaning: 'Nhật Bản' },
        ],
      },
      {
        id: 'naka',
        kanji: '中',
        hanViet: 'Trung',
        meaning: 'trong, giữa',
        onyomi: 'チュウ',
        kunyomi: 'なか',
        strokes: 4,
        icon: 'fas fa-bullseye',
        tone: 'rose',
        mnemonic: 'Một nét xuyên qua đúng tâm của chiếc hộp.',
        examples: [
          { word: '中', reading: 'なか', meaning: 'bên trong' },
          { word: '中国', reading: 'ちゅうごく', meaning: 'Trung Quốc' },
        ],
      },
    ],
  },
  {
    slug: 'bai-2',
    number: 2,
    title: 'Thời gian và chuyển động',
    japaneseTitle: '時間・行動',
    theme: '時・行・見',
    summary: 'Nhóm chữ dùng để nói thời gian, phía trước sau và hành động cơ bản.',
    focus: 'Đọc ví dụ theo cặp để thấy Kanji đổi âm khi ghép từ.',
    items: [
      {
        id: 'nagai',
        kanji: '長',
        hanViet: 'Trường',
        meaning: 'dài, trưởng',
        onyomi: 'チョウ',
        kunyomi: 'なが',
        strokes: 8,
        icon: 'fas fa-ruler-horizontal',
        tone: 'stone',
        mnemonic: 'Một đường dài được kéo xuống, gợi cảm giác dài ra.',
        examples: [
          { word: '長い', reading: 'ながい', meaning: 'dài' },
          { word: '社長', reading: 'しゃちょう', meaning: 'giám đốc công ty' },
        ],
      },
      {
        id: 'deru',
        kanji: '出',
        hanViet: 'Xuất',
        meaning: 'ra, xuất hiện',
        onyomi: 'シュツ',
        kunyomi: 'で、だ',
        strokes: 5,
        icon: 'fas fa-door-open',
        tone: 'sky',
        mnemonic: 'Hình vật nhô ra khỏi cửa, nhớ nghĩa đi ra.',
        examples: [
          { word: '出る', reading: 'でる', meaning: 'đi ra' },
          { word: '出口', reading: 'でぐち', meaning: 'lối ra' },
        ],
      },
      {
        id: 'san',
        kanji: '三',
        hanViet: 'Tam',
        meaning: 'ba',
        onyomi: 'サン',
        kunyomi: 'み',
        strokes: 3,
        icon: 'fas fa-bars',
        tone: 'ink',
        mnemonic: 'Ba nét ngang là số ba.',
        examples: [
          { word: '三つ', reading: 'みっつ', meaning: 'ba cái' },
          { word: '三月', reading: 'さんがつ', meaning: 'tháng ba' },
        ],
      },
      {
        id: 'toki',
        kanji: '時',
        hanViet: 'Thời',
        meaning: 'thời gian, giờ',
        onyomi: 'ジ',
        kunyomi: 'とき',
        strokes: 10,
        icon: 'fas fa-clock',
        tone: 'gold',
        mnemonic: 'Có 日 bên trái, liên tưởng mặt trời dùng để đo thời gian.',
        examples: [
          { word: '時間', reading: 'じかん', meaning: 'thời gian' },
          { word: '一時', reading: 'いちじ', meaning: 'một giờ' },
        ],
      },
      {
        id: 'iku',
        kanji: '行',
        hanViet: 'Hành',
        meaning: 'đi, hàng',
        onyomi: 'コウ、ギョウ',
        kunyomi: 'い、おこな',
        strokes: 6,
        icon: 'fas fa-person-walking',
        tone: 'leaf',
        mnemonic: 'Hai hàng đường như lối đi, nhớ nghĩa đi hoặc hàng lối.',
        examples: [
          { word: '行く', reading: 'いく', meaning: 'đi' },
          { word: '銀行', reading: 'ぎんこう', meaning: 'ngân hàng' },
        ],
      },
      {
        id: 'miru',
        kanji: '見',
        hanViet: 'Kiến',
        meaning: 'nhìn, xem, thấy',
        onyomi: 'ケン',
        kunyomi: 'み',
        strokes: 7,
        icon: 'fas fa-eye',
        tone: 'sky',
        mnemonic: 'Phía trên giống con mắt, phía dưới là chân đi để quan sát.',
        examples: [
          { word: '見る', reading: 'みる', meaning: 'xem, nhìn' },
          { word: '見学', reading: 'けんがく', meaning: 'tham quan học tập' },
        ],
      },
      {
        id: 'tsuki',
        kanji: '月',
        hanViet: 'Nguyệt',
        meaning: 'mặt trăng, tháng',
        onyomi: 'ゲツ、ガツ',
        kunyomi: 'つき',
        strokes: 4,
        icon: 'fas fa-moon',
        tone: 'sky',
        mnemonic: 'Hình vầng trăng khuyết được kẻ lại bằng nét thẳng.',
        examples: [
          { word: '月', reading: 'つき', meaning: 'mặt trăng' },
          { word: '一月', reading: 'いちがつ', meaning: 'tháng một' },
        ],
      },
      {
        id: 'wakaru',
        kanji: '分',
        hanViet: 'Phân',
        meaning: 'phần, phút, hiểu',
        onyomi: 'ブン、フン',
        kunyomi: 'わ',
        strokes: 4,
        icon: 'fas fa-divide',
        tone: 'rose',
        mnemonic: 'Tách một thứ ra thành phần nhỏ, từ đó nhớ nghĩa chia phần.',
        examples: [
          { word: '分かる', reading: 'わかる', meaning: 'hiểu' },
          { word: '五分', reading: 'ごふん', meaning: 'năm phút' },
        ],
      },
      {
        id: 'ato',
        kanji: '後',
        hanViet: 'Hậu',
        meaning: 'sau, phía sau',
        onyomi: 'ゴ、コウ',
        kunyomi: 'あと、うし',
        strokes: 9,
        icon: 'fas fa-backward-step',
        tone: 'stone',
        mnemonic: 'Nét bước chân đi phía sau, nhớ nghĩa sau đó.',
        examples: [
          { word: '後で', reading: 'あとで', meaning: 'sau đó' },
          { word: '午後', reading: 'ごご', meaning: 'buổi chiều' },
        ],
      },
      {
        id: 'mae',
        kanji: '前',
        hanViet: 'Tiền',
        meaning: 'trước, phía trước',
        onyomi: 'ゼン',
        kunyomi: 'まえ',
        strokes: 9,
        icon: 'fas fa-forward-step',
        tone: 'leaf',
        mnemonic: 'Nhớ cặp 前 - 後: trước và sau luôn đi cùng nhau.',
        examples: [
          { word: '前', reading: 'まえ', meaning: 'phía trước' },
          { word: '午前', reading: 'ごぜん', meaning: 'buổi sáng' },
        ],
      },
    ],
  },
  {
    slug: 'bai-3',
    number: 3,
    title: 'Đời sống, vị trí và tiền',
    japaneseTitle: '生活・場所・お金',
    theme: '生・上・金',
    summary: 'Những chữ thường gặp khi nói học tập, vị trí, thời điểm hiện tại và số đếm.',
    focus: 'Tập nhận diện bộ phận quen thuộc như 日, 門, 金 trong chữ ghép.',
    items: [
      {
        id: 'ikiru',
        kanji: '生',
        hanViet: 'Sinh',
        meaning: 'sống, sinh, học sinh',
        onyomi: 'セイ、ショウ',
        kunyomi: 'い、う、なま',
        strokes: 5,
        icon: 'fas fa-seedling',
        tone: 'leaf',
        mnemonic: 'Mầm cây mọc lên từ đất, nhớ nghĩa sinh ra và sự sống.',
        examples: [
          { word: '学生', reading: 'がくせい', meaning: 'học sinh, sinh viên' },
          { word: '先生', reading: 'せんせい', meaning: 'giáo viên' },
        ],
      },
      {
        id: 'go',
        kanji: '五',
        hanViet: 'Ngũ',
        meaning: 'năm',
        onyomi: 'ゴ',
        kunyomi: 'いつ',
        strokes: 4,
        icon: 'fas fa-hand',
        tone: 'rose',
        mnemonic: 'Một bàn tay có năm ngón, gắn với số 5.',
        examples: [
          { word: '五つ', reading: 'いつつ', meaning: 'năm cái' },
          { word: '五月', reading: 'ごがつ', meaning: 'tháng năm' },
        ],
      },
      {
        id: 'aida',
        kanji: '間',
        hanViet: 'Gian',
        meaning: 'khoảng, giữa, thời gian',
        onyomi: 'カン、ケン',
        kunyomi: 'あいだ、ま',
        strokes: 12,
        icon: 'fas fa-door-closed',
        tone: 'stone',
        mnemonic: 'Mặt trời 日 nằm trong cửa 門, tạo khoảng ở giữa.',
        examples: [
          { word: '時間', reading: 'じかん', meaning: 'thời gian' },
          { word: '間', reading: 'あいだ', meaning: 'ở giữa, khoảng' },
        ],
      },
      {
        id: 'ue',
        kanji: '上',
        hanViet: 'Thượng',
        meaning: 'trên, lên',
        onyomi: 'ジョウ',
        kunyomi: 'うえ、あ',
        strokes: 3,
        icon: 'fas fa-arrow-up',
        tone: 'sky',
        mnemonic: 'Nét chính nằm phía trên đường mốc, nhớ nghĩa ở trên.',
        examples: [
          { word: '上', reading: 'うえ', meaning: 'phía trên' },
          { word: '上手', reading: 'じょうず', meaning: 'giỏi, khéo' },
        ],
      },
      {
        id: 'higashi',
        kanji: '東',
        hanViet: 'Đông',
        meaning: 'hướng đông',
        onyomi: 'トウ',
        kunyomi: 'ひがし',
        strokes: 8,
        icon: 'fas fa-compass',
        tone: 'sun',
        mnemonic: 'Mặt trời mọc sau thân cây ở phía đông.',
        examples: [
          { word: '東', reading: 'ひがし', meaning: 'hướng đông' },
          { word: '東京', reading: 'とうきょう', meaning: 'Tokyo' },
        ],
      },
      {
        id: 'yon',
        kanji: '四',
        hanViet: 'Tứ',
        meaning: 'bốn',
        onyomi: 'シ',
        kunyomi: 'よん、よ',
        strokes: 5,
        icon: 'fas fa-dice-four',
        tone: 'ink',
        mnemonic: 'Một khung có bốn góc, nhớ số bốn.',
        examples: [
          { word: '四つ', reading: 'よっつ', meaning: 'bốn cái' },
          { word: '四月', reading: 'しがつ', meaning: 'tháng tư' },
        ],
      },
      {
        id: 'ima',
        kanji: '今',
        hanViet: 'Kim',
        meaning: 'bây giờ, hiện tại',
        onyomi: 'コン、キン',
        kunyomi: 'いま',
        strokes: 4,
        icon: 'fas fa-hourglass-half',
        tone: 'gold',
        mnemonic: 'Một nắp che ngay khoảnh khắc hiện tại: bây giờ.',
        examples: [
          { word: '今', reading: 'いま', meaning: 'bây giờ' },
          { word: '今日', reading: 'きょう', meaning: 'hôm nay' },
        ],
      },
      {
        id: 'kane',
        kanji: '金',
        hanViet: 'Kim',
        meaning: 'vàng, tiền, kim loại',
        onyomi: 'キン',
        kunyomi: 'かね',
        strokes: 8,
        icon: 'fas fa-coins',
        tone: 'gold',
        mnemonic: 'Những nét tụ lại như thỏi vàng, nhớ nghĩa tiền và kim loại.',
        examples: [
          { word: 'お金', reading: 'おかね', meaning: 'tiền' },
          { word: '金曜日', reading: 'きんようび', meaning: 'thứ sáu' },
        ],
      },
      {
        id: 'kyuu',
        kanji: '九',
        hanViet: 'Cửu',
        meaning: 'chín',
        onyomi: 'キュウ、ク',
        kunyomi: 'ここの',
        strokes: 2,
        icon: 'fas fa-rotate-right',
        tone: 'rose',
        mnemonic: 'Một nét cong kết lại, nhớ số gần tròn mười.',
        examples: [
          { word: '九つ', reading: 'ここのつ', meaning: 'chín cái' },
          { word: '九月', reading: 'くがつ', meaning: 'tháng chín' },
        ],
      },
      {
        id: 'hairu',
        kanji: '入',
        hanViet: 'Nhập',
        meaning: 'vào, nhập',
        onyomi: 'ニュウ',
        kunyomi: 'はい、い',
        strokes: 2,
        icon: 'fas fa-right-to-bracket',
        tone: 'leaf',
        mnemonic: 'Hai nét nghiêng như người bước vào cửa.',
        examples: [
          { word: '入る', reading: 'はいる', meaning: 'đi vào' },
          { word: '入口', reading: 'いりぐち', meaning: 'lối vào' },
        ],
      },
    ],
  },
  {
    slug: 'bai-4',
    number: 4,
    title: 'Trường học và kích thước',
    japaneseTitle: '学校・大きさ',
    theme: '学・高・小',
    summary: 'Nhóm chữ hữu ích khi nói trường lớp, vị trí trên dưới và trạng thái thời tiết.',
    focus: 'So sánh cặp trái nghĩa cao - thấp, lớn - nhỏ, trên - dưới.',
    items: [
      {
        id: 'manabu',
        kanji: '学',
        hanViet: 'Học',
        meaning: 'học, việc học',
        onyomi: 'ガク',
        kunyomi: 'まな',
        strokes: 8,
        icon: 'fas fa-graduation-cap',
        tone: 'sky',
        mnemonic: 'Một đứa trẻ 子 dưới mái lớp học, nhớ nghĩa học.',
        examples: [
          { word: '学生', reading: 'がくせい', meaning: 'học sinh, sinh viên' },
          { word: '学校', reading: 'がっこう', meaning: 'trường học' },
        ],
      },
      {
        id: 'takai',
        kanji: '高',
        hanViet: 'Cao',
        meaning: 'cao, đắt',
        onyomi: 'コウ',
        kunyomi: 'たか',
        strokes: 10,
        icon: 'fas fa-building',
        tone: 'stone',
        mnemonic: 'Nhìn như tòa nhà cao tầng, nhớ nghĩa cao.',
        examples: [
          { word: '高い', reading: 'たかい', meaning: 'cao, đắt' },
          { word: '高校', reading: 'こうこう', meaning: 'trường cấp ba' },
        ],
      },
      {
        id: 'en',
        kanji: '円',
        hanViet: 'Viên',
        meaning: 'yên, hình tròn',
        onyomi: 'エン',
        kunyomi: 'まる',
        strokes: 4,
        icon: 'fas fa-yen-sign',
        tone: 'gold',
        mnemonic: 'Đồng tiền tròn, nhớ nghĩa yên Nhật.',
        examples: [
          { word: '円', reading: 'えん', meaning: 'yên Nhật' },
          { word: '千円', reading: 'せんえん', meaning: 'một nghìn yên' },
        ],
      },
      {
        id: 'ko',
        kanji: '子',
        hanViet: 'Tử',
        meaning: 'trẻ em, con',
        onyomi: 'シ',
        kunyomi: 'こ',
        strokes: 3,
        icon: 'fas fa-child-reaching',
        tone: 'rose',
        mnemonic: 'Dáng một em bé dang tay, nhớ nghĩa trẻ em.',
        examples: [
          { word: '子ども', reading: 'こども', meaning: 'trẻ em' },
          { word: '女の子', reading: 'おんなのこ', meaning: 'bé gái' },
        ],
      },
      {
        id: 'soto',
        kanji: '外',
        hanViet: 'Ngoại',
        meaning: 'ngoài, bên ngoài',
        onyomi: 'ガイ、ゲ',
        kunyomi: 'そと、ほか',
        strokes: 5,
        icon: 'fas fa-person-through-window',
        tone: 'leaf',
        mnemonic: 'Đứng ngoài khung nhà, nhớ nghĩa bên ngoài.',
        examples: [
          { word: '外', reading: 'そと', meaning: 'bên ngoài' },
          { word: '外国人', reading: 'がいこくじん', meaning: 'người nước ngoài' },
        ],
      },
      {
        id: 'hachi',
        kanji: '八',
        hanViet: 'Bát',
        meaning: 'tám',
        onyomi: 'ハチ',
        kunyomi: 'や',
        strokes: 2,
        icon: 'fas fa-chevron-down',
        tone: 'ink',
        mnemonic: 'Hai nét tách rộng ra như số tám mở hai phía.',
        examples: [
          { word: '八つ', reading: 'やっつ', meaning: 'tám cái' },
          { word: '八月', reading: 'はちがつ', meaning: 'tháng tám' },
        ],
      },
      {
        id: 'roku',
        kanji: '六',
        hanViet: 'Lục',
        meaning: 'sáu',
        onyomi: 'ロク',
        kunyomi: 'む',
        strokes: 4,
        icon: 'fas fa-dice-six',
        tone: 'rose',
        mnemonic: 'Nhớ âm ロク đi cùng số 6 trong đếm tiếng Nhật.',
        examples: [
          { word: '六つ', reading: 'むっつ', meaning: 'sáu cái' },
          { word: '六月', reading: 'ろくがつ', meaning: 'tháng sáu' },
        ],
      },
      {
        id: 'shita',
        kanji: '下',
        hanViet: 'Hạ',
        meaning: 'dưới, xuống',
        onyomi: 'カ、ゲ',
        kunyomi: 'した、くだ',
        strokes: 3,
        icon: 'fas fa-arrow-down',
        tone: 'sky',
        mnemonic: 'Nét chính nằm phía dưới đường mốc, đối cặp với 上.',
        examples: [
          { word: '下', reading: 'した', meaning: 'phía dưới' },
          { word: '地下鉄', reading: 'ちかてつ', meaning: 'tàu điện ngầm' },
        ],
      },
      {
        id: 'kuru',
        kanji: '来',
        hanViet: 'Lai',
        meaning: 'đến, tới',
        onyomi: 'ライ',
        kunyomi: 'く',
        strokes: 7,
        icon: 'fas fa-person-walking-arrow-right',
        tone: 'leaf',
        mnemonic: 'Một người tiến lại gần, nhớ động từ đến.',
        examples: [
          { word: '来る', reading: 'くる', meaning: 'đến' },
          { word: '来年', reading: 'らいねん', meaning: 'năm sau' },
        ],
      },
      {
        id: 'ki-air',
        kanji: '気',
        hanViet: 'Khí',
        meaning: 'khí, tinh thần, tâm trạng',
        onyomi: 'キ',
        kunyomi: 'け',
        strokes: 6,
        icon: 'fas fa-wind',
        tone: 'water',
        mnemonic: 'Những nét như luồng không khí chuyển động.',
        examples: [
          { word: '元気', reading: 'げんき', meaning: 'khỏe, khỏe khoắn' },
          { word: '天気', reading: 'てんき', meaning: 'thời tiết' },
        ],
      },
    ],
  },
  {
    slug: 'bai-5',
    number: 5,
    title: 'Thiên nhiên và giao tiếp',
    japaneseTitle: '自然・会話',
    theme: '山・話・書',
    summary: 'Ghép số đếm, phương hướng, gia đình và các động từ học tập cơ bản.',
    focus: 'Tập phân biệt 女, 男 và các chữ chỉ phương hướng.',
    items: [
      {
        id: 'chiisai',
        kanji: '小',
        hanViet: 'Tiểu',
        meaning: 'nhỏ',
        onyomi: 'ショウ',
        kunyomi: 'ちい、こ',
        strokes: 3,
        icon: 'fas fa-compress',
        tone: 'leaf',
        mnemonic: 'Một nét chính nhỏ với hai chấm hai bên, nhớ nghĩa nhỏ.',
        examples: [
          { word: '小さい', reading: 'ちいさい', meaning: 'nhỏ' },
          { word: '小学校', reading: 'しょうがっこう', meaning: 'trường tiểu học' },
        ],
      },
      {
        id: 'nana',
        kanji: '七',
        hanViet: 'Thất',
        meaning: 'bảy',
        onyomi: 'シチ',
        kunyomi: 'なな',
        strokes: 2,
        icon: 'fas fa-7',
        tone: 'rose',
        mnemonic: 'Nhớ cặp đọc なな và しち trong ngày tháng.',
        examples: [
          { word: '七つ', reading: 'ななつ', meaning: 'bảy cái' },
          { word: '七月', reading: 'しちがつ', meaning: 'tháng bảy' },
        ],
      },
      {
        id: 'yama',
        kanji: '山',
        hanViet: 'Sơn',
        meaning: 'núi',
        onyomi: 'サン',
        kunyomi: 'やま',
        strokes: 3,
        icon: 'fas fa-mountain',
        tone: 'stone',
        mnemonic: 'Ba đỉnh núi dựng lên rất rõ.',
        examples: [
          { word: '山', reading: 'やま', meaning: 'núi' },
          { word: '富士山', reading: 'ふじさん', meaning: 'núi Phú Sĩ' },
        ],
      },
      {
        id: 'hanasu',
        kanji: '話',
        hanViet: 'Thoại',
        meaning: 'nói chuyện, câu chuyện',
        onyomi: 'ワ',
        kunyomi: 'はな、はなし',
        strokes: 13,
        icon: 'fas fa-comments',
        tone: 'sky',
        mnemonic: 'Có 言 bên trái, liên tưởng lời nói và hội thoại.',
        examples: [
          { word: '話す', reading: 'はなす', meaning: 'nói chuyện' },
          { word: '会話', reading: 'かいわ', meaning: 'hội thoại' },
        ],
      },
      {
        id: 'onna',
        kanji: '女',
        hanViet: 'Nữ',
        meaning: 'phụ nữ, nữ',
        onyomi: 'ジョ',
        kunyomi: 'おんな',
        strokes: 3,
        icon: 'fas fa-venus',
        tone: 'rose',
        mnemonic: 'Một dáng người mềm với nét vắt chéo, nhớ nghĩa nữ.',
        examples: [
          { word: '女', reading: 'おんな', meaning: 'phụ nữ' },
          { word: '女の子', reading: 'おんなのこ', meaning: 'bé gái' },
        ],
      },
      {
        id: 'kita',
        kanji: '北',
        hanViet: 'Bắc',
        meaning: 'hướng bắc',
        onyomi: 'ホク',
        kunyomi: 'きた',
        strokes: 5,
        icon: 'fas fa-location-arrow',
        tone: 'water',
        mnemonic: 'Hai người quay lưng, gợi hướng đối lập trên bản đồ.',
        examples: [
          { word: '北', reading: 'きた', meaning: 'hướng bắc' },
          { word: '北海道', reading: 'ほっかいどう', meaning: 'Hokkaido' },
        ],
      },
      {
        id: 'go-noon',
        kanji: '午',
        hanViet: 'Ngọ',
        meaning: 'buổi trưa',
        onyomi: 'ゴ',
        kunyomi: 'うま',
        strokes: 4,
        icon: 'fas fa-mug-hot',
        tone: 'sun',
        mnemonic: 'Gắn với mốc giữa ngày trong 午前 và 午後.',
        examples: [
          { word: '午前', reading: 'ごぜん', meaning: 'buổi sáng' },
          { word: '午後', reading: 'ごご', meaning: 'buổi chiều' },
        ],
      },
      {
        id: 'hyaku',
        kanji: '百',
        hanViet: 'Bách',
        meaning: 'một trăm',
        onyomi: 'ヒャク',
        kunyomi: 'もも',
        strokes: 6,
        icon: 'fas fa-100',
        tone: 'gold',
        mnemonic: 'Nhớ âm ヒャク khi đếm tiền và số lượng lớn.',
        examples: [
          { word: '百', reading: 'ひゃく', meaning: 'một trăm' },
          { word: '三百', reading: 'さんびゃく', meaning: 'ba trăm' },
        ],
      },
      {
        id: 'kaku',
        kanji: '書',
        hanViet: 'Thư',
        meaning: 'viết, sách vở',
        onyomi: 'ショ',
        kunyomi: 'か',
        strokes: 10,
        icon: 'fas fa-pen-nib',
        tone: 'ink',
        mnemonic: 'Các nét xếp như bút viết lên giấy.',
        examples: [
          { word: '書く', reading: 'かく', meaning: 'viết' },
          { word: '辞書', reading: 'じしょ', meaning: 'từ điển' },
        ],
      },
      {
        id: 'saki',
        kanji: '先',
        hanViet: 'Tiên',
        meaning: 'trước, trước tiên',
        onyomi: 'セン',
        kunyomi: 'さき',
        strokes: 6,
        icon: 'fas fa-forward',
        tone: 'leaf',
        mnemonic: 'Người đi đầu ở phía trước, nhớ nghĩa trước tiên.',
        examples: [
          { word: '先生', reading: 'せんせい', meaning: 'giáo viên' },
          { word: '先月', reading: 'せんげつ', meaning: 'tháng trước' },
        ],
      },
    ],
  },
  {
    slug: 'bai-6',
    number: 6,
    title: 'Tên gọi, nước và trường lớp',
    japaneseTitle: '名前・水・学校',
    theme: '名・水・語',
    summary: 'Các chữ dùng trong tên, địa hình, tiền bạc, giới tính và môn tiếng Nhật.',
    focus: 'Nhớ chữ theo cụm quen thuộc: 名前, 日本語, 学校, 電車.',
    items: [
      {
        id: 'na',
        kanji: '名',
        hanViet: 'Danh',
        meaning: 'tên, danh',
        onyomi: 'メイ、ミョウ',
        kunyomi: 'な',
        strokes: 6,
        icon: 'fas fa-id-badge',
        tone: 'rose',
        mnemonic: 'Tên được gọi ra bằng miệng 口 vào buổi tối 夕.',
        examples: [
          { word: '名前', reading: 'なまえ', meaning: 'tên' },
          { word: '有名', reading: 'ゆうめい', meaning: 'nổi tiếng' },
        ],
      },
      {
        id: 'kawa',
        kanji: '川',
        hanViet: 'Xuyên',
        meaning: 'sông',
        onyomi: 'セン',
        kunyomi: 'かわ',
        strokes: 3,
        icon: 'fas fa-water',
        tone: 'water',
        mnemonic: 'Ba dòng nước chảy song song thành con sông.',
        examples: [
          { word: '川', reading: 'かわ', meaning: 'sông' },
          { word: '小川', reading: 'おがわ', meaning: 'suối nhỏ' },
        ],
      },
      {
        id: 'sen',
        kanji: '千',
        hanViet: 'Thiên',
        meaning: 'một nghìn',
        onyomi: 'セン',
        kunyomi: 'ち',
        strokes: 3,
        icon: 'fas fa-money-bill-1',
        tone: 'gold',
        mnemonic: 'Nhớ theo cụm 千円, mệnh giá rất hay gặp ở Nhật.',
        examples: [
          { word: '千', reading: 'せん', meaning: 'một nghìn' },
          { word: '千円', reading: 'せんえん', meaning: 'một nghìn yên' },
        ],
      },
      {
        id: 'mizu',
        kanji: '水',
        hanViet: 'Thủy',
        meaning: 'nước',
        onyomi: 'スイ',
        kunyomi: 'みず',
        strokes: 4,
        icon: 'fas fa-droplet',
        tone: 'water',
        mnemonic: 'Dòng nước văng ra hai bên từ nét giữa.',
        examples: [
          { word: '水', reading: 'みず', meaning: 'nước' },
          { word: '水曜日', reading: 'すいようび', meaning: 'thứ tư' },
        ],
      },
      {
        id: 'han',
        kanji: '半',
        hanViet: 'Bán',
        meaning: 'một nửa',
        onyomi: 'ハン',
        kunyomi: 'なか',
        strokes: 5,
        icon: 'fas fa-circle-half-stroke',
        tone: 'ink',
        mnemonic: 'Một vật được chia làm hai nửa.',
        examples: [
          { word: '半分', reading: 'はんぶん', meaning: 'một nửa' },
          { word: '三時半', reading: 'さんじはん', meaning: 'ba giờ rưỡi' },
        ],
      },
      {
        id: 'otoko',
        kanji: '男',
        hanViet: 'Nam',
        meaning: 'đàn ông, nam',
        onyomi: 'ダン、ナン',
        kunyomi: 'おとこ',
        strokes: 7,
        icon: 'fas fa-mars',
        tone: 'stone',
        mnemonic: 'Ruộng 田 và sức 力, cách ghi nhớ cổ về người nam lao động.',
        examples: [
          { word: '男', reading: 'おとこ', meaning: 'đàn ông' },
          { word: '男の子', reading: 'おとこのこ', meaning: 'bé trai' },
        ],
      },
      {
        id: 'nishi',
        kanji: '西',
        hanViet: 'Tây',
        meaning: 'hướng tây',
        onyomi: 'セイ、サイ',
        kunyomi: 'にし',
        strokes: 6,
        icon: 'fas fa-compass',
        tone: 'sun',
        mnemonic: 'Mặt trời lặn về phía tây, nhớ hướng 西.',
        examples: [
          { word: '西', reading: 'にし', meaning: 'hướng tây' },
          { word: '関西', reading: 'かんさい', meaning: 'vùng Kansai' },
        ],
      },
      {
        id: 'den',
        kanji: '電',
        hanViet: 'Điện',
        meaning: 'điện',
        onyomi: 'デン',
        kunyomi: '-',
        strokes: 13,
        icon: 'fas fa-bolt',
        tone: 'gold',
        mnemonic: 'Có 雨 ở trên như sấm chớp, liên tưởng điện.',
        examples: [
          { word: '電車', reading: 'でんしゃ', meaning: 'tàu điện' },
          { word: '電話', reading: 'でんわ', meaning: 'điện thoại' },
        ],
      },
      {
        id: 'kou-school',
        kanji: '校',
        hanViet: 'Hiệu',
        meaning: 'trường học',
        onyomi: 'コウ',
        kunyomi: '-',
        strokes: 10,
        icon: 'fas fa-school',
        tone: 'leaf',
        mnemonic: 'Đi với 学 thành 学校, cụm bắt buộc nhớ ở N5.',
        examples: [
          { word: '学校', reading: 'がっこう', meaning: 'trường học' },
          { word: '高校', reading: 'こうこう', meaning: 'trường cấp ba' },
        ],
      },
      {
        id: 'go-language',
        kanji: '語',
        hanViet: 'Ngữ',
        meaning: 'ngôn ngữ, lời nói',
        onyomi: 'ゴ',
        kunyomi: 'かた',
        strokes: 14,
        icon: 'fas fa-language',
        tone: 'sky',
        mnemonic: 'Có 言 bên trái, liên hệ trực tiếp với lời nói và ngôn ngữ.',
        examples: [
          { word: '日本語', reading: 'にほんご', meaning: 'tiếng Nhật' },
          { word: '英語', reading: 'えいご', meaning: 'tiếng Anh' },
        ],
      },
    ],
  },
  {
    slug: 'bai-7',
    number: 7,
    title: 'Đất, cây, ăn uống và phương hướng',
    japaneseTitle: '土・木・食べ物',
    theme: '土・木・食',
    summary: 'Nhóm chữ đời sống hằng ngày: ngày trong tuần, ăn uống, xe cộ, câu hỏi và màu sắc.',
    focus: 'Tập đọc to các ví dụ vì nhiều chữ đổi âm khi đứng trong từ ghép.',
    items: [
      {
        id: 'tsuchi',
        kanji: '土',
        hanViet: 'Thổ',
        meaning: 'đất',
        onyomi: 'ド、ト',
        kunyomi: 'つち',
        strokes: 3,
        icon: 'fas fa-mound',
        tone: 'stone',
        mnemonic: 'Nét ngang dưới là mặt đất, nét dọc cắm vào đất.',
        examples: [
          { word: '土', reading: 'つち', meaning: 'đất' },
          { word: '土曜日', reading: 'どようび', meaning: 'thứ bảy' },
        ],
      },
      {
        id: 'ki',
        kanji: '木',
        hanViet: 'Mộc',
        meaning: 'cây, gỗ',
        onyomi: 'モク、ボク',
        kunyomi: 'き',
        strokes: 4,
        icon: 'fas fa-tree',
        tone: 'leaf',
        mnemonic: 'Một thân cây với cành vươn hai bên.',
        examples: [
          { word: '木', reading: 'き', meaning: 'cây' },
          { word: '木曜日', reading: 'もくようび', meaning: 'thứ năm' },
        ],
      },
      {
        id: 'kiku',
        kanji: '聞',
        hanViet: 'Văn',
        meaning: 'nghe, hỏi',
        onyomi: 'ブン、モン',
        kunyomi: 'き',
        strokes: 14,
        icon: 'fas fa-ear-listen',
        tone: 'sky',
        mnemonic: 'Tai 耳 nằm trong cửa 門, ghé tai để nghe.',
        examples: [
          { word: '聞く', reading: 'きく', meaning: 'nghe, hỏi' },
          { word: '新聞', reading: 'しんぶん', meaning: 'báo' },
        ],
      },
      {
        id: 'taberu',
        kanji: '食',
        hanViet: 'Thực',
        meaning: 'ăn, thức ăn',
        onyomi: 'ショク',
        kunyomi: 'た、く',
        strokes: 9,
        icon: 'fas fa-bowl-food',
        tone: 'gold',
        mnemonic: 'Nhớ như chiếc nắp đậy trên bát thức ăn.',
        examples: [
          { word: '食べる', reading: 'たべる', meaning: 'ăn' },
          { word: '食堂', reading: 'しょくどう', meaning: 'nhà ăn' },
        ],
      },
      {
        id: 'kuruma',
        kanji: '車',
        hanViet: 'Xa',
        meaning: 'xe',
        onyomi: 'シャ',
        kunyomi: 'くるま',
        strokes: 7,
        icon: 'fas fa-train-subway',
        tone: 'rose',
        mnemonic: 'Hình bánh và trục xe được giản lược thành nét thẳng.',
        examples: [
          { word: '車', reading: 'くるま', meaning: 'xe hơi' },
          { word: '電車', reading: 'でんしゃ', meaning: 'tàu điện' },
        ],
      },
      {
        id: 'nani',
        kanji: '何',
        hanViet: 'Hà',
        meaning: 'cái gì',
        onyomi: 'カ',
        kunyomi: 'なに、なん',
        strokes: 7,
        icon: 'fas fa-circle-question',
        tone: 'sky',
        mnemonic: 'Nhớ như câu hỏi hay dùng nhất: 何ですか.',
        examples: [
          { word: '何', reading: 'なに', meaning: 'cái gì' },
          { word: '何人', reading: 'なんにん', meaning: 'mấy người' },
        ],
      },
      {
        id: 'minami',
        kanji: '南',
        hanViet: 'Nam',
        meaning: 'hướng nam',
        onyomi: 'ナン',
        kunyomi: 'みなみ',
        strokes: 9,
        icon: 'fas fa-map-location-dot',
        tone: 'sun',
        mnemonic: 'Phía nam thường gắn với nắng ấm trong bản đồ khí hậu.',
        examples: [
          { word: '南', reading: 'みなみ', meaning: 'hướng nam' },
          { word: '南口', reading: 'みなみぐち', meaning: 'cửa nam' },
        ],
      },
      {
        id: 'man',
        kanji: '万',
        hanViet: 'Vạn',
        meaning: 'mười nghìn',
        onyomi: 'マン、バン',
        kunyomi: '-',
        strokes: 3,
        icon: 'fas fa-sack-dollar',
        tone: 'gold',
        mnemonic: 'Rất hay gặp khi nói tiền lương, giá cả ở Nhật.',
        examples: [
          { word: '一万', reading: 'いちまん', meaning: 'mười nghìn' },
          { word: '万年筆', reading: 'まんねんひつ', meaning: 'bút máy' },
        ],
      },
      {
        id: 'mai',
        kanji: '毎',
        hanViet: 'Mỗi',
        meaning: 'mỗi, hằng',
        onyomi: 'マイ',
        kunyomi: 'ごと',
        strokes: 6,
        icon: 'fas fa-repeat',
        tone: 'leaf',
        mnemonic: 'Lặp lại đều đặn, nhớ nghĩa mỗi ngày, mỗi tuần.',
        examples: [
          { word: '毎日', reading: 'まいにち', meaning: 'mỗi ngày' },
          { word: '毎朝', reading: 'まいあさ', meaning: 'mỗi sáng' },
        ],
      },
      {
        id: 'shiro',
        kanji: '白',
        hanViet: 'Bạch',
        meaning: 'trắng',
        onyomi: 'ハク',
        kunyomi: 'しろ、しら',
        strokes: 5,
        icon: 'fas fa-cloud',
        tone: 'sky',
        mnemonic: 'Mặt trời 日 thêm nét sáng ở trên, liên tưởng màu trắng.',
        examples: [
          { word: '白い', reading: 'しろい', meaning: 'màu trắng' },
          { word: '面白い', reading: 'おもしろい', meaning: 'thú vị' },
        ],
      },
    ],
  },
  {
    slug: 'bai-8',
    number: 8,
    title: 'Gia đình, đọc viết và thời tiết',
    japaneseTitle: '家族・読む・天気',
    theme: '天・母・雨',
    summary: 'Hoàn tất 80 chữ N5 bằng nhóm gia đình, phương hướng trái phải và thời tiết.',
    focus: 'Ôn theo cặp: 父 - 母, 左 - 右, 読 - 書.',
    items: [
      {
        id: 'ten',
        kanji: '天',
        hanViet: 'Thiên',
        meaning: 'trời, bầu trời',
        onyomi: 'テン',
        kunyomi: 'あま',
        strokes: 4,
        icon: 'fas fa-cloud-sun',
        tone: 'sky',
        mnemonic: 'Một người 大 đứng dưới vạch trời 一.',
        examples: [
          { word: '天気', reading: 'てんき', meaning: 'thời tiết' },
          { word: '天ぷら', reading: 'てんぷら', meaning: 'tempura' },
        ],
      },
      {
        id: 'haha',
        kanji: '母',
        hanViet: 'Mẫu',
        meaning: 'mẹ',
        onyomi: 'ボ',
        kunyomi: 'はは、かあ',
        strokes: 5,
        icon: 'fas fa-person-breastfeeding',
        tone: 'rose',
        mnemonic: 'Nhớ theo cặp 父 - 母 để học từ gia đình.',
        examples: [
          { word: '母', reading: 'はは', meaning: 'mẹ tôi' },
          { word: 'お母さん', reading: 'おかあさん', meaning: 'mẹ' },
        ],
      },
      {
        id: 'hi-fire',
        kanji: '火',
        hanViet: 'Hỏa',
        meaning: 'lửa',
        onyomi: 'カ',
        kunyomi: 'ひ',
        strokes: 4,
        icon: 'fas fa-fire',
        tone: 'rose',
        mnemonic: 'Ngọn lửa bốc lên với hai tia lửa hai bên.',
        examples: [
          { word: '火', reading: 'ひ', meaning: 'lửa' },
          { word: '火曜日', reading: 'かようび', meaning: 'thứ ba' },
        ],
      },
      {
        id: 'migi',
        kanji: '右',
        hanViet: 'Hữu',
        meaning: 'bên phải',
        onyomi: 'ウ、ユウ',
        kunyomi: 'みぎ',
        strokes: 5,
        icon: 'fas fa-arrow-right',
        tone: 'leaf',
        mnemonic: 'Nhớ 右 có 口 ở dưới, phân biệt với 左 có 工.',
        examples: [
          { word: '右', reading: 'みぎ', meaning: 'bên phải' },
          { word: '右手', reading: 'みぎて', meaning: 'tay phải' },
        ],
      },
      {
        id: 'yomu',
        kanji: '読',
        hanViet: 'Độc',
        meaning: 'đọc',
        onyomi: 'ドク',
        kunyomi: 'よ',
        strokes: 14,
        icon: 'fas fa-book-open-reader',
        tone: 'ink',
        mnemonic: 'Có 言 bên trái, liên hệ đọc chữ và lời.',
        examples: [
          { word: '読む', reading: 'よむ', meaning: 'đọc' },
          { word: '読書', reading: 'どくしょ', meaning: 'đọc sách' },
        ],
      },
      {
        id: 'tomo',
        kanji: '友',
        hanViet: 'Hữu',
        meaning: 'bạn bè',
        onyomi: 'ユウ',
        kunyomi: 'とも',
        strokes: 4,
        icon: 'fas fa-user-group',
        tone: 'sky',
        mnemonic: 'Hai bàn tay gặp nhau, nhớ nghĩa bạn bè.',
        examples: [
          { word: '友だち', reading: 'ともだち', meaning: 'bạn bè' },
          { word: '親友', reading: 'しんゆう', meaning: 'bạn thân' },
        ],
      },
      {
        id: 'hidari',
        kanji: '左',
        hanViet: 'Tả',
        meaning: 'bên trái',
        onyomi: 'サ',
        kunyomi: 'ひだり',
        strokes: 5,
        icon: 'fas fa-arrow-left',
        tone: 'water',
        mnemonic: 'Nhớ 左 có 工 ở dưới, đối với 右 có 口.',
        examples: [
          { word: '左', reading: 'ひだり', meaning: 'bên trái' },
          { word: '左手', reading: 'ひだりて', meaning: 'tay trái' },
        ],
      },
      {
        id: 'yasumu',
        kanji: '休',
        hanViet: 'Hưu',
        meaning: 'nghỉ ngơi',
        onyomi: 'キュウ',
        kunyomi: 'やす',
        strokes: 6,
        icon: 'fas fa-bed',
        tone: 'leaf',
        mnemonic: 'Người 亻 đứng cạnh cây 木 để nghỉ mát.',
        examples: [
          { word: '休む', reading: 'やすむ', meaning: 'nghỉ' },
          { word: '休み', reading: 'やすみ', meaning: 'ngày nghỉ' },
        ],
      },
      {
        id: 'chichi',
        kanji: '父',
        hanViet: 'Phụ',
        meaning: 'bố',
        onyomi: 'フ',
        kunyomi: 'ちち、とう',
        strokes: 4,
        icon: 'fas fa-person',
        tone: 'stone',
        mnemonic: 'Nhớ theo cụm お父さん và đối cặp với 母.',
        examples: [
          { word: '父', reading: 'ちち', meaning: 'bố tôi' },
          { word: 'お父さん', reading: 'おとうさん', meaning: 'bố' },
        ],
      },
      {
        id: 'ame',
        kanji: '雨',
        hanViet: 'Vũ',
        meaning: 'mưa',
        onyomi: 'ウ',
        kunyomi: 'あめ',
        strokes: 8,
        icon: 'fas fa-cloud-rain',
        tone: 'water',
        mnemonic: 'Các chấm rơi xuống từ mái trời, giống hạt mưa.',
        examples: [
          { word: '雨', reading: 'あめ', meaning: 'mưa' },
          { word: '大雨', reading: 'おおあめ', meaning: 'mưa lớn' },
        ],
      },
    ],
  },
];

type KanjiN5LessonPlan = Omit<KanjiN5Lesson, 'items'> & {
  itemIds: string[];
};

const KANJI_N5_LESSON_PLAN: KanjiN5LessonPlan[] = [
  {
    slug: 'bai-1',
    number: 1,
    title: 'Nét đơn giản và hình dễ nhớ',
    japaneseTitle: '基本・形',
    theme: '一・人・山',
    summary: 'Bắt đầu bằng chữ ít nét, hình dáng dễ liên tưởng và rất hay gặp khi mới học.',
    focus: 'Nhìn mặt chữ trước, sau đó đọc ví dụ để nhớ nghĩa.',
    itemIds: ['ichi', 'ni', 'san', 'juu', 'hito', 'hairu', 'ookii', 'chiisai', 'yama', 'kawa'],
  },
  {
    slug: 'bai-2',
    number: 2,
    title: 'Số đếm và tiền',
    japaneseTitle: '数字・お金',
    theme: '四・百・円',
    summary: 'Hoàn thiện nhóm số cơ bản, số lớn và chữ dùng khi nói tiền yên Nhật.',
    focus: 'Học theo dãy số để não nhận ra quy luật nhanh hơn.',
    itemIds: ['yon', 'go', 'roku', 'nana', 'hachi', 'kyuu', 'hyaku', 'sen', 'man', 'en'],
  },
  {
    slug: 'bai-3',
    number: 3,
    title: 'Ngày tháng và tuần',
    japaneseTitle: '日付・曜日',
    theme: '日・月・年',
    summary: 'Nhóm chữ xuất hiện liên tục trong lịch, ngày trong tuần, tháng và mốc thời gian.',
    focus: 'Ghép với ví dụ ngày trong tuần để nhớ âm On thường gặp.',
    itemIds: ['nichi', 'tsuki', 'hi-fire', 'mizu', 'ki', 'kane', 'tsuchi', 'toshi', 'ima', 'go-noon'],
  },
  {
    slug: 'bai-4',
    number: 4,
    title: 'Vị trí và phương hướng',
    japaneseTitle: '位置・方向',
    theme: '上・右・南',
    summary: 'Học các cặp trên dưới, trước sau, trái phải và hướng thường dùng khi chỉ đường.',
    focus: 'Học theo cặp đối nhau để dễ phân biệt mặt chữ.',
    itemIds: ['ue', 'shita', 'naka', 'mae', 'migi', 'hidari', 'higashi', 'nishi', 'kita', 'minami'],
  },
  {
    slug: 'bai-5',
    number: 5,
    title: 'Ra vào và hành động',
    japaneseTitle: '移動・動作',
    theme: '外・行・読',
    summary: 'Các chữ chỉ bên ngoài, phía sau, di chuyển và hành động dùng nhiều trong câu N5 hằng ngày.',
    focus: 'Đọc to ví dụ dạng động từ để nhớ cả nghĩa và cách dùng.',
    itemIds: ['ato', 'soto', 'deru', 'iku', 'kuru', 'miru', 'kiku', 'hanasu', 'kaku', 'yomu'],
  },
  {
    slug: 'bai-6',
    number: 6,
    title: 'Con người, gia đình và học tập',
    japaneseTitle: '人・家族・学校',
    theme: '子・父・学',
    summary: 'Nhóm chữ dùng khi giới thiệu bản thân, gia đình, bạn bè và chuyện học tập.',
    focus: 'Nhớ theo cụm quen thuộc như 学生, 先生, 名前, 友だち.',
    itemIds: ['ko', 'onna', 'otoko', 'chichi', 'haha', 'tomo', 'na', 'saki', 'ikiru', 'manabu'],
  },
  {
    slug: 'bai-7',
    number: 7,
    title: 'Đời sống và giao tiếp hằng ngày',
    japaneseTitle: '生活・会話',
    theme: '本・語・車',
    summary: 'Các chữ dùng nhiều trong học tập, giao tiếp, đi lại, ăn uống và câu hỏi.',
    focus: 'Ưu tiên nhớ từ ghép thường gặp trong JLPT N5 và N4 thấp.',
    itemIds: ['hon', 'kou-school', 'go-language', 'kuni', 'den', 'kuruma', 'taberu', 'nani', 'mai', 'han'],
  },
  {
    slug: 'bai-8',
    number: 8,
    title: 'Thời gian, tính chất và tự nhiên',
    japaneseTitle: '時間・自然',
    theme: '時・長・天',
    summary: 'Những chữ nhiều nét hơn hoặc nghĩa trừu tượng hơn, học sau khi đã quen mặt chữ cơ bản.',
    focus: 'Ôn kỹ nét viết và từ vựng liên quan để tránh nhầm chữ phức tạp.',
    itemIds: ['wakaru', 'toki', 'aida', 'nagai', 'takai', 'ki-air', 'ten', 'ame', 'shiro', 'yasumu'],
  },
];

const KANJI_N5_ITEM_BY_ID = new Map(
  KANJI_N5_SOURCE_LESSONS.flatMap((lesson) => lesson.items).map((item) => [item.id, item]),
);

const kanjiItemById = (id: string): KanjiN5Item => {
  const item = KANJI_N5_ITEM_BY_ID.get(id);
  if (!item) {
    throw new Error(`Missing Kanji N5 item: ${id}`);
  }
  return item;
};

export const KANJI_N5_LESSONS: KanjiN5Lesson[] = KANJI_N5_LESSON_PLAN.map(
  ({ itemIds, ...lesson }) => ({
    ...lesson,
    items: itemIds.map(kanjiItemById),
  }),
);

export const KANJI_N5_TOTAL = KANJI_N5_LESSONS.reduce(
  (total, lesson) => total + lesson.items.length,
  0,
);
