// ============================================================
//  POTENTIAL FORM (THỂ KHẢ NĂNG / 可能形 - KANOUKEI) — DATA
// ============================================================

export interface PotentialFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  potentialForm: string; // Dạng khả năng hiragana (e.g. かえる, たべられる, できる, こられる)
  potentialFormKanji: string; // Dạng khả năng kanji (e.g. 買える, 食べられる, 出来る, 来られる)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const POTENTIAL_FORM_VERBS: PotentialFormVerb[] = [
  // ── NHÓM 1: Đổi âm cột い sang cột え + る (五段動詞) ───────
  // 1. Kết thúc い → える
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    potentialForm: 'かえる',
    potentialFormKanji: '買える',
    meaning: 'Có thể mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    potentialForm: 'あえる',
    potentialFormKanji: '会える',
    meaning: 'Có thể gặp',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },
  {
    id: 'suu',
    kanji: '吸います',
    hiragana: 'すいます',
    potentialForm: 'すえる',
    potentialFormKanji: '吸える',
    meaning: 'Có thể hút',
    hanViet: 'HẤP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    potentialForm: 'つかえる',
    potentialFormKanji: '使える',
    meaning: 'Có thể sử dụng / dùng được',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    potentialForm: 'うたえる',
    potentialFormKanji: '歌える',
    meaning: 'Có thể hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    potentialForm: 'はらえる',
    potentialFormKanji: '払える',
    meaning: 'Có thể chi trả',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eru',
  },

  // 2. Kết thúc き → ける
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    potentialForm: 'いける',
    potentialFormKanji: '行ける',
    meaning: 'Có thể đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    potentialForm: 'かける',
    potentialFormKanji: '書ける',
    meaning: 'Có thể viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    potentialForm: 'きける',
    potentialFormKanji: '聞ける',
    meaning: 'Có thể nghe / hỏi',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    potentialForm: 'はたらける',
    potentialFormKanji: '働ける',
    meaning: 'Có thể làm việc',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    potentialForm: 'あるける',
    potentialFormKanji: '歩ける',
    meaning: 'Có thể đi bộ',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },
  {
    id: 'oku',
    kanji: '置きます',
    hiragana: 'おきます',
    potentialForm: 'おける',
    potentialFormKanji: '置ける',
    meaning: 'Có thể để / đặt',
    hanViet: 'TRÍ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keru',
  },

  // 3. Kết thúc ぎ → げる
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    potentialForm: 'およげる',
    potentialFormKanji: '泳げる',
    meaning: 'Có thể bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geru',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    potentialForm: 'いそげる',
    potentialFormKanji: '急げる',
    meaning: 'Có thể khẩn trương',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geru',
  },
  {
    id: 'nugu',
    kanji: '脱ぎます',
    hiragana: 'ぬぎます',
    potentialForm: 'ぬげる',
    potentialFormKanji: '脱げる',
    meaning: 'Có thể cởi',
    hanViet: 'THOÁT',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geru',
  },

  // 4. Kết thúc し → せる
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    potentialForm: 'はなせる',
    potentialFormKanji: '話せる',
    meaning: 'Có thể nói chuyện',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seru',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    potentialForm: 'だせる',
    potentialFormKanji: '出せる',
    meaning: 'Có thể đưa ra / nộp',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seru',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    potentialForm: 'けせる',
    potentialFormKanji: '消せる',
    meaning: 'Có thể tắt / xóa',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seru',
  },
  {
    id: 'naosu',
    kanji: '直します',
    hiragana: 'なおします',
    potentialForm: 'なおせる',
    potentialFormKanji: '直せる',
    meaning: 'Có thể sửa chữa',
    hanViet: 'TRỰC',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seru',
  },
  {
    id: 'kasu',
    kanji: '貸します',
    hiragana: 'かします',
    potentialForm: 'かせれる',
    potentialFormKanji: '貸せる',
    meaning: 'Có thể cho mượn',
    hanViet: 'THẢI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seru',
  },

  // 5. Kết thúc ち → てる
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    potentialForm: 'まてる',
    potentialFormKanji: '待てる',
    meaning: 'Có thể chờ đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teru',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    potentialForm: 'たてる',
    potentialFormKanji: '立てる',
    meaning: 'Có thể đứng',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teru',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    potentialForm: 'もてる',
    potentialFormKanji: '持てる',
    meaning: 'Có thể cầm / có sức hút',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teru',
  },

  // 6. Kết thúc に → ねる
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    potentialForm: 'しねる',
    potentialFormKanji: '死ねる',
    meaning: 'Có thể chết',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_neru',
  },

  // 7. Kết thúc び → べる
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    potentialForm: 'あそべる',
    potentialFormKanji: '遊べる',
    meaning: 'Có thể chơi',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beru',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    potentialForm: 'よべる',
    potentialFormKanji: '呼べる',
    meaning: 'Có thể gọi',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beru',
  },
  {
    id: 'tobu',
    kanji: '飛びます',
    hiragana: 'とびます',
    potentialForm: 'とべる',
    potentialFormKanji: '飛べる',
    meaning: 'Có thể bay / nhảy',
    hanViet: 'PHI',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beru',
  },

  // 8. Kết thúc み → める
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    potentialForm: 'のめる',
    potentialFormKanji: '飲める',
    meaning: 'Có thể uống',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meru',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    potentialForm: 'よめる',
    potentialFormKanji: '読める',
    meaning: 'Có thể đọc',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meru',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    potentialForm: 'やすめる',
    potentialFormKanji: '休める',
    meaning: 'Có thể nghỉ ngơi',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meru',
  },
  {
    id: 'sumu',
    kanji: '住みます',
    hiragana: 'すみます',
    potentialForm: 'すめる',
    potentialFormKanji: '住める',
    meaning: 'Có thể sinh sống',
    hanViet: 'TRÚ',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meru',
  },

  // 9. Kết thúc り → れる
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    potentialForm: 'かえれる',
    potentialFormKanji: '帰れる',
    meaning: 'Có thể về',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reru',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    potentialForm: 'つくれる',
    potentialFormKanji: '作れる',
    meaning: 'Có thể làm / chế tạo',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reru',
  },
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    potentialForm: 'はしれる',
    potentialFormKanji: '走れる',
    meaning: 'Có thể chạy',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reru',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    potentialForm: 'とれる',
    potentialFormKanji: '取れる',
    meaning: 'Có thể lấy / bắt được',
    hanViet: 'THỦ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reru',
  },
  {
    id: 'hairu',
    kanji: '入ります',
    hiragana: 'はいります',
    potentialForm: 'はいれる',
    potentialFormKanji: '入れる',
    meaning: 'Có thể vào',
    hanViet: 'NHẬP',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reru',
  },

  // ── NHÓM 2: Bỏ ます → Thêm られる (一段動詞) ───────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    potentialForm: 'たべられる',
    potentialFormKanji: '食べられる',
    meaning: 'Có thể ăn',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_rareru',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    potentialForm: 'みられる',
    potentialFormKanji: '見られる',
    meaning: 'Có thể xem / nhìn (theo ý muốn)',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_rareru',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    potentialForm: 'おきられる',
    potentialFormKanji: '起きられる',
    meaning: 'Có thể thức dậy',
    hanViet: 'KHỞI',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_rareru',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    potentialForm: 'ねられる',
    potentialFormKanji: '寝られる',
    meaning: 'Có thể ngủ',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_rareru',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    potentialForm: 'あけられる',
    potentialFormKanji: '開けられる',
    meaning: 'Có thể mở',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_rareru',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    potentialForm: 'しめられる',
    potentialFormKanji: '閉められる',
    meaning: 'Có thể đóng',
    hanViet: 'BẾ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_rareru',
  },
  {
    id: 'oboeru',
    kanji: '覚えます',
    hiragana: 'おぼえます',
    potentialForm: 'おぼえられる',
    potentialFormKanji: '覚えられる',
    meaning: 'Có thể ghi nhớ',
    hanViet: 'GIÁC',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_rareru',
  },
  {
    id: 'wasureru',
    kanji: '忘れます',
    hiragana: 'わすれます',
    potentialForm: 'わすれられる',
    potentialFormKanji: '忘れられる',
    meaning: 'Có thể quên được',
    hanViet: 'VONG',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_rareru',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    potentialForm: 'おしえられる',
    potentialFormKanji: '教えられる',
    meaning: 'Có thể chỉ dạy',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_rareru',
  },
  {
    id: 'kaeru2',
    kanji: '変えます',
    hiragana: 'かえます',
    potentialForm: 'かえられる',
    potentialFormKanji: '変えられる',
    meaning: 'Có thể thay đổi',
    hanViet: 'BIẾN',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_rareru',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    potentialForm: 'できる',
    potentialFormKanji: '出来る',
    meaning: 'Có thể làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_dekiru',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    potentialForm: 'べんきょうできる',
    potentialFormKanji: '勉強出来る',
    meaning: 'Có thể học tập',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_dekiru',
  },
  {
    id: 'untensuru',
    kanji: '運転します',
    hiragana: 'うんてんします',
    potentialForm: 'うんてんできる',
    potentialFormKanji: '運転出来る',
    meaning: 'Có thể lái xe',
    hanViet: 'VẬN CHUYỂN',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_dekiru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    potentialForm: 'こられる',
    potentialFormKanji: '来られる',
    meaning: 'Có thể đến',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru_korareru',
  },
];
