// ============================================================
//  CONDITIONAL FORM (THỂ ĐIỀU KIỆN / 条件形 - JOUKENKEI / ば) — DATA
// ============================================================

export interface ConditionalFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  conditionalForm: string; // Dạng điều kiện hiragana (e.g. かえば, たべれば, すれば, くれば)
  conditionalFormKanji: string; // Dạng điều kiện kanji (e.g. 買えば, 食べれば, すれば, 来れば)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const CONDITIONAL_FORM_VERBS: ConditionalFormVerb[] = [
  // ── NHÓM 1: Đổi âm cột い sang cột え + ば (五段動詞) ───────
  // 1. Kết thúc い → えば
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    conditionalForm: 'かえば',
    conditionalFormKanji: '買えば',
    meaning: 'Nếu mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    conditionalForm: 'あえば',
    conditionalFormKanji: '会えば',
    meaning: 'Nếu gặp',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'suu',
    kanji: '吸います',
    hiragana: 'すいます',
    conditionalForm: 'すえば',
    conditionalFormKanji: '吸えば',
    meaning: 'Nếu hút (thuốc)',
    hanViet: 'HẤP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    conditionalForm: 'つかえば',
    conditionalFormKanji: '使えば',
    meaning: 'Nếu sử dụng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    conditionalForm: 'うたえば',
    conditionalFormKanji: '歌えば',
    meaning: 'Nếu hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    conditionalForm: 'はらえば',
    conditionalFormKanji: '払えば',
    meaning: 'Nếu trả tiền',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },
  {
    id: 'narau',
    kanji: '習います',
    hiragana: 'ならいます',
    conditionalForm: 'ならえば',
    conditionalFormKanji: '習えば',
    meaning: 'Nếu học tập',
    hanViet: 'TẬP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_eba',
  },

  // 2. Kết thúc き → けば
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    conditionalForm: 'いけば',
    conditionalFormKanji: '行けば',
    meaning: 'Nếu đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    conditionalForm: 'かけば',
    conditionalFormKanji: '書けば',
    meaning: 'Nếu viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    conditionalForm: 'きけば',
    conditionalFormKanji: '聞けば',
    meaning: 'Nếu nghe / hỏi',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    conditionalForm: 'はたらけば',
    conditionalFormKanji: '働けば',
    meaning: 'Nếu làm việc',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    conditionalForm: 'あるけば',
    conditionalFormKanji: '歩けば',
    meaning: 'Nếu đi bộ',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },
  {
    id: 'oku',
    kanji: '置きます',
    hiragana: 'おきます',
    conditionalForm: 'おけば',
    conditionalFormKanji: '置けば',
    meaning: 'Nếu để / đặt',
    hanViet: 'TRÍ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_keba',
  },

  // 3. Kết thúc ぎ → げば
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    conditionalForm: 'およげば',
    conditionalFormKanji: '泳げば',
    meaning: 'Nếu bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geba',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    conditionalForm: 'いそげば',
    conditionalFormKanji: '急げば',
    meaning: 'Nếu vội / khẩn trương',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geba',
  },
  {
    id: 'nugu',
    kanji: '脱ぎます',
    hiragana: 'ぬぎます',
    conditionalForm: 'ぬげば',
    conditionalFormKanji: '脱げば',
    meaning: 'Nếu cởi ra',
    hanViet: 'THOÁT',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_geba',
  },

  // 4. Kết thúc し → せば
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    conditionalForm: 'はなせば',
    conditionalFormKanji: '話せば',
    meaning: 'Nếu nói chuyện',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    conditionalForm: 'だせば',
    conditionalFormKanji: '出せば',
    meaning: 'Nếu nộp / đưa ra',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    conditionalForm: 'けせば',
    conditionalFormKanji: '消せば',
    meaning: 'Nếu tắt / xóa',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },
  {
    id: 'kasu',
    kanji: '貸します',
    hiragana: 'かします',
    conditionalForm: 'かせば',
    conditionalFormKanji: '貸せば',
    meaning: 'Nếu cho mượn',
    hanViet: 'THẢI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },
  {
    id: 'naosu',
    kanji: '直します',
    hiragana: 'なおします',
    conditionalForm: 'なおせば',
    conditionalFormKanji: '直せば',
    meaning: 'Nếu sửa chữa',
    hanViet: 'TRỰC',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },
  {
    id: 'osu',
    kanji: '押します',
    hiragana: 'おします',
    conditionalForm: 'おせば',
    conditionalFormKanji: '押せば',
    meaning: 'Nếu ấn / đẩy',
    hanViet: 'ÁP',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_seba',
  },

  // 5. Kết thúc ち → てば
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    conditionalForm: 'まてば',
    conditionalFormKanji: '待てば',
    meaning: 'Nếu đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teba',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    conditionalForm: 'たてば',
    conditionalFormKanji: '立てば',
    meaning: 'Nếu đứng dậy',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teba',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    conditionalForm: 'もてば',
    conditionalFormKanji: '持てば',
    meaning: 'Nếu mang theo',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_teba',
  },

  // 6. Kết thúc に → ねば
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    conditionalForm: 'しねば',
    conditionalFormKanji: '死ねば',
    meaning: 'Nếu chết',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_neba',
  },

  // 7. Kết thúc び → べば
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    conditionalForm: 'あそべば',
    conditionalFormKanji: '遊べば',
    meaning: 'Nếu chơi',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beba',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    conditionalForm: 'よべば',
    conditionalFormKanji: '呼べば',
    meaning: 'Nếu gọi',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beba',
  },
  {
    id: 'tobu',
    kanji: '飛びます',
    hiragana: 'とびます',
    conditionalForm: 'とべば',
    conditionalFormKanji: '飛べば',
    meaning: 'Nếu bay / nhảy',
    hanViet: 'PHI',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_beba',
  },

  // 8. Kết thúc み → めば
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    conditionalForm: 'のめば',
    conditionalFormKanji: '飲めば',
    meaning: 'Nếu uống',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meba',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    conditionalForm: 'よめば',
    conditionalFormKanji: '読めば',
    meaning: 'Nếu đọc',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meba',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    conditionalForm: 'やすめば',
    conditionalFormKanji: '休めば',
    meaning: 'Nếu nghỉ ngơi',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meba',
  },
  {
    id: 'sumu',
    kanji: '住みます',
    hiragana: 'すみます',
    conditionalForm: 'すめば',
    conditionalFormKanji: '住めば',
    meaning: 'Nếu sinh sống',
    hanViet: 'TRÚ',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_meba',
  },

  // 9. Kết thúc り → れば
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    conditionalForm: 'かえれば',
    conditionalFormKanji: '帰れば',
    meaning: 'Nếu về',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    conditionalForm: 'つくれば',
    conditionalFormKanji: '作れば',
    meaning: 'Nếu làm / tạo ra',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    conditionalForm: 'はしれば',
    conditionalFormKanji: '走れば',
    meaning: 'Nếu chạy',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    conditionalForm: 'とれば',
    conditionalFormKanji: '取れば',
    meaning: 'Nếu lấy / chụp',
    hanViet: 'THỦ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },
  {
    id: 'hairu',
    kanji: '入ります',
    hiragana: 'はいります',
    conditionalForm: 'はいれば',
    conditionalFormKanji: '入れば',
    meaning: 'Nếu vào',
    hanViet: 'NHẬP',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },
  {
    id: 'ganbaru',
    kanji: '頑張ります',
    hiragana: 'がんばります',
    conditionalForm: 'がんばれば',
    conditionalFormKanji: '頑張れば',
    meaning: 'Nếu cố gắng',
    hanViet: 'NGOAN TRƯƠNG',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_reba',
  },

  // ── NHÓM 2: Bỏ ます → Thêm れば (一段動詞) ─────────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    conditionalForm: 'たべれば',
    conditionalFormKanji: '食べれば',
    meaning: 'Nếu ăn',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_reba',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    conditionalForm: 'みれば',
    conditionalFormKanji: '見れば',
    meaning: 'Nếu xem / nhìn',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_reba',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    conditionalForm: 'おきれば',
    conditionalFormKanji: '起きれば',
    meaning: 'Nếu thức dậy',
    hanViet: 'KHỞI',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_reba',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    conditionalForm: 'ねれば',
    conditionalFormKanji: '寝れば',
    meaning: 'Nếu ngủ',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_reba',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    conditionalForm: 'あければ',
    conditionalFormKanji: '開ければ',
    meaning: 'Nếu mở',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_reba',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    conditionalForm: 'しめれば',
    conditionalFormKanji: '閉めれば',
    meaning: 'Nếu đóng',
    hanViet: 'BẾ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_reba',
  },
  {
    id: 'oboeru',
    kanji: '覚えます',
    hiragana: 'おぼえます',
    conditionalForm: 'おぼえれば',
    conditionalFormKanji: '覚えれば',
    meaning: 'Nếu ghi nhớ',
    hanViet: 'GIÁC',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_reba',
  },
  {
    id: 'wasureru',
    kanji: '忘れます',
    hiragana: 'わすれます',
    conditionalForm: 'わすれれば',
    conditionalFormKanji: '忘れれば',
    meaning: 'Nếu quên',
    hanViet: 'VONG',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_reba',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    conditionalForm: 'おしえれば',
    conditionalFormKanji: '教えれば',
    meaning: 'Nếu chỉ dạy',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_reba',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    conditionalForm: 'すれば',
    conditionalFormKanji: 'すれば',
    meaning: 'Nếu làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_sureba',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    conditionalForm: 'べんきょうすれば',
    conditionalFormKanji: '勉強すれば',
    meaning: 'Nếu học tập',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_sureba',
  },
  {
    id: 'untensuru',
    kanji: '運転します',
    hiragana: 'うんてんします',
    conditionalForm: 'うんてんすれば',
    conditionalFormKanji: '運転すれば',
    meaning: 'Nếu lái xe',
    hanViet: 'VẬN CHUYỂN',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_sureba',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    conditionalForm: 'くれば',
    conditionalFormKanji: '来れば',
    meaning: 'Nếu đến (⚠️ đọc là ku-re-ba)',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kureba',
  },
];
