// ============================================================
//  PROHIBITIVE FORM (THỂ CẤM CHỈ / 禁止形 - KINSHIKEI / な) — DATA
// ============================================================

export interface ProhibitiveFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  prohibitiveForm: string; // Dạng cấm chỉ hiragana (e.g. かうな, たべるな, くるな)
  prohibitiveFormKanji: string; // Dạng cấm chỉ kanji (e.g. 買うな, 食べるな, 来るな)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const PROHIBITIVE_FORM_VERBS: ProhibitiveFormVerb[] = [
  // ── NHÓM 1: Đổi sang Thể Từ Điển (る/u) + な (五段動詞) ─────
  // 1. Kết thúc い → う + な
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    prohibitiveForm: 'かうな',
    prohibitiveFormKanji: '買うな',
    meaning: 'Cấm mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },
  {
    id: 'suu',
    kanji: '吸います',
    hiragana: 'すいます',
    prohibitiveForm: 'すうな',
    prohibitiveFormKanji: '吸うな',
    meaning: 'Cấm hút (thuốc)',
    hanViet: 'HẤP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    prohibitiveForm: 'あうな',
    prohibitiveFormKanji: '会うな',
    meaning: 'Cấm gặp',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    prohibitiveForm: 'つかうな',
    prohibitiveFormKanji: '使うな',
    meaning: 'Cấm dùng / sử dụng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    prohibitiveForm: 'うたうな',
    prohibitiveFormKanji: '歌うな',
    meaning: 'Cấm hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    prohibitiveForm: 'はらうな',
    prohibitiveFormKanji: '払うな',
    meaning: 'Cấm trả tiền',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_u_na',
  },

  // 2. Kết thúc き → く + な
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    prohibitiveForm: 'いくな',
    prohibitiveFormKanji: '行くな',
    meaning: 'Cấm đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    prohibitiveForm: 'かくな',
    prohibitiveFormKanji: '書くな',
    meaning: 'Cấm viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    prohibitiveForm: 'きくな',
    prohibitiveFormKanji: '聞くな',
    meaning: 'Cấm nghe / hỏi',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },
  {
    id: 'oku',
    kanji: '置きます',
    hiragana: 'おきます',
    prohibitiveForm: 'おくな',
    prohibitiveFormKanji: '置くな',
    meaning: 'Cấm để / đặt ở đây',
    hanViet: 'TRÍ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    prohibitiveForm: 'はたらくな',
    prohibitiveFormKanji: '働くな',
    meaning: 'Cấm làm việc',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    prohibitiveForm: 'あるくな',
    prohibitiveFormKanji: '歩くな',
    meaning: 'Cấm đi bộ',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ku_na',
  },

  // 3. Kết thúc ぎ → ぐ + な
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    prohibitiveForm: 'およぐな',
    prohibitiveFormKanji: '泳ぐな',
    meaning: 'Cấm bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gu_na',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    prohibitiveForm: 'いそぐな',
    prohibitiveFormKanji: '急ぐな',
    meaning: 'Cấm vội vã',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gu_na',
  },
  {
    id: 'nugu',
    kanji: '脱ぎます',
    hiragana: 'ぬぎます',
    prohibitiveForm: 'ぬぐな',
    prohibitiveFormKanji: '脱ぐな',
    meaning: 'Cấm cởi (đồ)',
    hanViet: 'THOÁT',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gu_na',
  },

  // 4. Kết thúc し → す + な
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    prohibitiveForm: 'はなすな',
    prohibitiveFormKanji: '話すな',
    meaning: 'Cấm nói chuyện',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_su_na',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    prohibitiveForm: 'だすな',
    prohibitiveFormKanji: '出すな',
    meaning: 'Cấm thò ra / đưa ra',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_su_na',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    prohibitiveForm: 'けすな',
    prohibitiveFormKanji: '消すな',
    meaning: 'Cấm tắt / xóa',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_su_na',
  },
  {
    id: 'osu',
    kanji: '押します',
    hiragana: 'おします',
    prohibitiveForm: 'おすな',
    prohibitiveFormKanji: '押すな',
    meaning: 'Cấm ấn / xô đẩy',
    hanViet: 'ÁP',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_su_na',
  },
  {
    id: 'kasu',
    kanji: '貸します',
    hiragana: 'かします',
    prohibitiveForm: 'かすな',
    prohibitiveFormKanji: '貸すな',
    meaning: 'Cấm cho mượn',
    hanViet: 'THẢI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_su_na',
  },

  // 5. Kết thúc ち → つ + な
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    prohibitiveForm: 'たつな',
    prohibitiveFormKanji: '立つな',
    meaning: 'Cấm đứng',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tsu_na',
  },
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    prohibitiveForm: 'まつな',
    prohibitiveFormKanji: '待つな',
    meaning: 'Cấm đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tsu_na',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    prohibitiveForm: 'もつな',
    prohibitiveFormKanji: '持つな',
    meaning: 'Cấm cầm / mang theo',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_tsu_na',
  },

  // 6. Kết thúc に → ぬ + な
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    prohibitiveForm: 'しぬな',
    prohibitiveFormKanji: '死ぬな',
    meaning: 'Cấm chết / Đừng chết!',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_nu_na',
  },

  // 7. Kết thúc び → ぶ + な
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    prohibitiveForm: 'あそぶな',
    prohibitiveFormKanji: '遊ぶな',
    meaning: 'Cấm chơi đùa',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bu_na',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    prohibitiveForm: 'よぶな',
    prohibitiveFormKanji: '呼ぶな',
    meaning: 'Cấm gọi',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bu_na',
  },
  {
    id: 'tobu',
    kanji: '飛びます',
    hiragana: 'とびます',
    prohibitiveForm: 'とぶな',
    prohibitiveFormKanji: '飛ぶな',
    meaning: 'Cấm nhảy / bay',
    hanViet: 'PHI',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bu_na',
  },

  // 8. Kết thúc み → む + な
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    prohibitiveForm: 'のむな',
    prohibitiveFormKanji: '飲むな',
    meaning: 'Cấm uống',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mu_na',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    prohibitiveForm: 'よむな',
    prohibitiveFormKanji: '読むな',
    meaning: 'Cấm đọc',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mu_na',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    prohibitiveForm: 'やすむな',
    prohibitiveFormKanji: '休むな',
    meaning: 'Cấm nghỉ',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mu_na',
  },

  // 9. Kết thúc り → る + な
  {
    id: 'hairu',
    kanji: '入ります',
    hiragana: 'はいります',
    prohibitiveForm: 'はいるな',
    prohibitiveFormKanji: '入るな',
    meaning: 'Cấm vào (biển báo 入るな)',
    hanViet: 'NHẬP',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },
  {
    id: 'sawaru',
    kanji: '触ります',
    hiragana: 'さわります',
    prohibitiveForm: 'さわるな',
    prohibitiveFormKanji: '触るな',
    meaning: 'Cấm sờ / chạm vào',
    hanViet: 'XÚC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },
  {
    id: 'toru',
    kanji: '撮ります',
    hiragana: 'とります',
    prohibitiveForm: 'とるな',
    prohibitiveFormKanji: '撮るな',
    meaning: 'Cấm chụp ảnh',
    hanViet: 'TOÁT',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },
  {
    id: 'tomaru',
    kanji: '止まります',
    hiragana: 'とまります',
    prohibitiveForm: 'とまるな',
    prohibitiveFormKanji: '止まるな',
    meaning: 'Cấm dừng lại',
    hanViet: 'CHỈ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    prohibitiveForm: 'はしるな',
    prohibitiveFormKanji: '走るな',
    meaning: 'Cấm chạy',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    prohibitiveForm: 'かえるな',
    prohibitiveFormKanji: '帰るな',
    meaning: 'Cấm về',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ru_na',
  },

  // ── NHÓM 2: Bỏ ます → Thêm る + な (一段動詞) ───────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    prohibitiveForm: 'たべるな',
    prohibitiveFormKanji: '食べるな',
    meaning: 'Cấm ăn',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_ru_na',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    prohibitiveForm: 'みるな',
    prohibitiveFormKanji: '見るな',
    meaning: 'Cấm nhìn / xem',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_ru_na',
  },
  {
    id: 'suteru',
    kanji: '捨てます',
    hiragana: 'すてます',
    prohibitiveForm: 'すてるな',
    prohibitiveFormKanji: '捨てるな',
    meaning: 'Cấm vứt rác',
    hanViet: 'XẢ',
    group: 2,
    endingBefore: 'て',
    rule: 'g2_ru_na',
  },
  {
    id: 'tomeru',
    kanji: '止めます',
    hiragana: 'とめます',
    prohibitiveForm: 'とめるな',
    prohibitiveFormKanji: '止めるな',
    meaning: 'Cấm đỗ xe / dừng lại',
    hanViet: 'CHỈ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_ru_na',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    prohibitiveForm: 'あけるな',
    prohibitiveFormKanji: '開けるな',
    meaning: 'Cấm mở (cửa)',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_ru_na',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    prohibitiveForm: 'しめるな',
    prohibitiveFormKanji: '閉めるな',
    meaning: 'Cấm đóng (cửa)',
    hanViet: 'BẾ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_ru_na',
  },
  {
    id: 'wasureru',
    kanji: '忘れます',
    hiragana: 'わすれます',
    prohibitiveForm: 'わすれるな',
    prohibitiveFormKanji: '忘れるな',
    meaning: 'Cấm quên / Đừng quên!',
    hanViet: 'VONG',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_ru_na',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    prohibitiveForm: 'ねるな',
    prohibitiveFormKanji: '寝るな',
    meaning: 'Cấm ngủ gật',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_ru_na',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    prohibitiveForm: 'するな',
    prohibitiveFormKanji: 'するな',
    meaning: 'Cấm làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_na',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    prohibitiveForm: 'べんきょうするな',
    prohibitiveFormKanji: '勉強するな',
    meaning: 'Cấm học',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_na',
  },
  {
    id: 'chuushasuru',
    kanji: '駐車します',
    hiragana: 'ちゅうしゃします',
    prohibitiveForm: 'ちゅうしゃするな',
    prohibitiveFormKanji: '駐車するな',
    meaning: 'Cấm đỗ xe (biển 駐車禁止)',
    hanViet: 'TRÚ XA',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_na',
  },
  {
    id: 'untensuru',
    kanji: '運転します',
    hiragana: 'うんてんします',
    prohibitiveForm: 'うんてんするな',
    prohibitiveFormKanji: '運転するな',
    meaning: 'Cấm lái xe',
    hanViet: 'VẬN CHUYỂN',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru_na',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    prohibitiveForm: 'くるな',
    prohibitiveFormKanji: '来るな',
    meaning: 'Cấm đến / Đừng lại đây!',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru_na',
  },
];
