// ============================================================
//  IMPERATIVE FORM (THỂ MỆNH LỆNH / 命令形 - MEIREIKEI) — DATA
// ============================================================

export interface ImperativeFormVerb {
  id: string;
  kanji: string;
  hiragana: string;
  imperativeForm: string; // Dạng mệnh lệnh hiragana (e.g. いけ, たべろ, こい)
  imperativeFormKanji: string; // Dạng mệnh lệnh kanji (e.g. 行け, 食べろ, 来い)
  meaning: string; // Nghĩa tiếng Việt
  hanViet?: string; // Âm Hán Việt
  group: 1 | 2 | 3; // Nhóm động từ
  endingBefore: string; // Ký tự trước ます (e.g. 'き', 'し', 'ち', 'り'...)
  rule: string; // Mã quy tắc
}

export const IMPERATIVE_FORM_VERBS: ImperativeFormVerb[] = [
  // ── NHÓM 1: Đổi âm cột い sang cột え (五段動詞) ────────────
  // 1. Kết thúc い → え
  {
    id: 'kau',
    kanji: '買います',
    hiragana: 'かいます',
    imperativeForm: 'かえ',
    imperativeFormKanji: '買え',
    meaning: 'Mua',
    hanViet: 'MÃI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'au',
    kanji: '会います',
    hiragana: 'あいます',
    imperativeForm: 'あえ',
    imperativeFormKanji: '会え',
    meaning: 'Gặp',
    hanViet: 'HỘI',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'suu',
    kanji: '吸います',
    hiragana: 'すいます',
    imperativeForm: 'すえ',
    imperativeFormKanji: '吸え',
    meaning: 'Hút (thuốc)',
    hanViet: 'HẤP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'utau',
    kanji: '歌います',
    hiragana: 'うたいます',
    imperativeForm: 'うたえ',
    imperativeFormKanji: '歌え',
    meaning: 'Hát',
    hanViet: 'CA',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'tsukau',
    kanji: '使います',
    hiragana: 'つかいます',
    imperativeForm: 'つかえ',
    imperativeFormKanji: '使え',
    meaning: 'Sử dụng',
    hanViet: 'SỬ',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'narau',
    kanji: '習います',
    hiragana: 'ならいます',
    imperativeForm: 'ならえ',
    imperativeFormKanji: '習え',
    meaning: 'Học tập (từ ai đó)',
    hanViet: 'TẬP',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'harau',
    kanji: '払います',
    hiragana: 'はらいます',
    imperativeForm: 'はらえ',
    imperativeFormKanji: '払え',
    meaning: 'Trả tiền',
    hanViet: 'PHẤT',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },
  {
    id: 'morau',
    kanji: '貰います',
    hiragana: 'もらいます',
    imperativeForm: 'もらえ',
    imperativeFormKanji: '貰え',
    meaning: 'Nhận',
    group: 1,
    endingBefore: 'い',
    rule: 'g1_i_e',
  },

  // 2. Kết thúc き → け
  {
    id: 'kaku',
    kanji: '書きます',
    hiragana: 'かきます',
    imperativeForm: 'かけ',
    imperativeFormKanji: '書け',
    meaning: 'Viết',
    hanViet: 'THƯ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },
  {
    id: 'kiku',
    kanji: '聞きます',
    hiragana: 'ききます',
    imperativeForm: 'きけ',
    imperativeFormKanji: '聞け',
    meaning: 'Nghe, hỏi',
    hanViet: 'VĂN',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },
  {
    id: 'iku',
    kanji: '行きます',
    hiragana: 'いきます',
    imperativeForm: 'いけ',
    imperativeFormKanji: '行け',
    meaning: 'Đi',
    hanViet: 'HÀNH',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },
  {
    id: 'hataraku',
    kanji: '働きます',
    hiragana: 'はたらきます',
    imperativeForm: 'はたらけ',
    imperativeFormKanji: '働け',
    meaning: 'Làm việc',
    hanViet: 'ĐỘNG',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },
  {
    id: 'aruku',
    kanji: '歩きます',
    hiragana: 'あるきます',
    imperativeForm: 'あるけ',
    imperativeFormKanji: '歩け',
    meaning: 'Đi bộ',
    hanViet: 'BỘ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },
  {
    id: 'oku',
    kanji: '置きます',
    hiragana: 'おきます',
    imperativeForm: 'おけ',
    imperativeFormKanji: '置け',
    meaning: 'Đặt, để',
    hanViet: 'TRÍ',
    group: 1,
    endingBefore: 'き',
    rule: 'g1_ki_ke',
  },

  // 3. Kết thúc ぎ → げ
  {
    id: 'oyogu',
    kanji: '泳ぎます',
    hiragana: 'およぎます',
    imperativeForm: 'およげ',
    imperativeFormKanji: '泳げ',
    meaning: 'Bơi',
    hanViet: 'VỊNH',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gi_ge',
  },
  {
    id: 'isogu',
    kanji: '急ぎます',
    hiragana: 'いそぎます',
    imperativeForm: 'いそげ',
    imperativeFormKanji: '急げ',
    meaning: 'Khẩn trương, vội',
    hanViet: 'CẤP',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gi_ge',
  },
  {
    id: 'nugu',
    kanji: '脱ぎます',
    hiragana: 'ぬぎます',
    imperativeForm: 'ぬげ',
    imperativeFormKanji: '脱げ',
    meaning: 'Cởi (quần áo, giày)',
    hanViet: 'THOÁT',
    group: 1,
    endingBefore: 'ぎ',
    rule: 'g1_gi_ge',
  },

  // 4. Kết thúc し → せ
  {
    id: 'hanasu',
    kanji: '話します',
    hiragana: 'はなします',
    imperativeForm: 'はなせ',
    imperativeFormKanji: '話せ',
    meaning: 'Nói chuyện',
    hanViet: 'THOẠI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },
  {
    id: 'dasu',
    kanji: '出します',
    hiragana: 'だします',
    imperativeForm: 'だせ',
    imperativeFormKanji: '出せ',
    meaning: 'Đưa ra, nộp',
    hanViet: 'XUẤT',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },
  {
    id: 'kesu',
    kanji: '消します',
    hiragana: 'けします',
    imperativeForm: 'けせ',
    imperativeFormKanji: '消せ',
    meaning: 'Tắt (điện), xóa',
    hanViet: 'TIÊU',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },
  {
    id: 'kasu',
    kanji: '貸します',
    hiragana: 'かします',
    imperativeForm: 'かせ',
    imperativeFormKanji: '貸せ',
    meaning: 'Cho mượn',
    hanViet: 'THẢI',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },
  {
    id: 'naosu',
    kanji: '直します',
    hiragana: 'なおします',
    imperativeForm: 'なおせ',
    imperativeFormKanji: '直せ',
    meaning: 'Sửa chữa',
    hanViet: 'TRỰC',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },
  {
    id: 'osu',
    kanji: '押します',
    hiragana: 'おします',
    imperativeForm: 'おせ',
    imperativeFormKanji: '押せ',
    meaning: 'Ấn, đẩy',
    hanViet: 'ÁP',
    group: 1,
    endingBefore: 'し',
    rule: 'g1_shi_se',
  },

  // 5. Kết thúc ち → て
  {
    id: 'matsu',
    kanji: '待ちます',
    hiragana: 'まちます',
    imperativeForm: 'まて',
    imperativeFormKanji: '待て',
    meaning: 'Chờ, đợi',
    hanViet: 'ĐÃI',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_te',
  },
  {
    id: 'tatsu',
    kanji: '立ちます',
    hiragana: 'たちます',
    imperativeForm: 'たて',
    imperativeFormKanji: '立て',
    meaning: 'Đứng',
    hanViet: 'LẬP',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_te',
  },
  {
    id: 'motsu',
    kanji: '持ちます',
    hiragana: 'もちます',
    imperativeForm: 'もて',
    imperativeFormKanji: '持て',
    meaning: 'Cầm, mang',
    hanViet: 'TRÌ',
    group: 1,
    endingBefore: 'ち',
    rule: 'g1_chi_te',
  },

  // 6. Kết thúc に → ね
  {
    id: 'shinu',
    kanji: '死にます',
    hiragana: 'しにます',
    imperativeForm: 'しね',
    imperativeFormKanji: '死ね',
    meaning: 'Chết',
    hanViet: 'TỬ',
    group: 1,
    endingBefore: 'に',
    rule: 'g1_ni_ne',
  },

  // 7. Kết thúc び → べ
  {
    id: 'asobu',
    kanji: '遊びます',
    hiragana: 'あそびます',
    imperativeForm: 'あそべ',
    imperativeFormKanji: '遊べ',
    meaning: 'Chơi',
    hanViet: 'DU',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_be',
  },
  {
    id: 'yobu',
    kanji: '呼びます',
    hiragana: 'よびます',
    imperativeForm: 'よべ',
    imperativeFormKanji: '呼べ',
    meaning: 'Gọi',
    hanViet: 'HÔ',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_be',
  },
  {
    id: 'tobu',
    kanji: '飛びます',
    hiragana: 'とびます',
    imperativeForm: 'とべ',
    imperativeFormKanji: '飛べ',
    meaning: 'Bay, nhảy',
    hanViet: 'PHI',
    group: 1,
    endingBefore: 'び',
    rule: 'g1_bi_be',
  },

  // 8. Kết thúc み → め
  {
    id: 'nomu',
    kanji: '飲みます',
    hiragana: 'のみます',
    imperativeForm: 'のめ',
    imperativeFormKanji: '飲め',
    meaning: 'Uống',
    hanViet: 'ẨM',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_me',
  },
  {
    id: 'yomu',
    kanji: '読みます',
    hiragana: 'よみます',
    imperativeForm: 'よめ',
    imperativeFormKanji: '読め',
    meaning: 'Đọc',
    hanViet: 'ĐỘC',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_me',
  },
  {
    id: 'yasumu',
    kanji: '休みます',
    hiragana: 'やすみます',
    imperativeForm: 'やすめ',
    imperativeFormKanji: '休め',
    meaning: 'Nghỉ ngơi',
    hanViet: 'HƯU',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_me',
  },
  {
    id: 'sumu',
    kanji: '住みます',
    hiragana: 'すみます',
    imperativeForm: 'すめ',
    imperativeFormKanji: '住め',
    meaning: 'Sinh sống',
    hanViet: 'TRÚ',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_me',
  },
  {
    id: 'tanomu',
    kanji: '頼みます',
    hiragana: 'たのみます',
    imperativeForm: 'たのめ',
    imperativeFormKanji: '頼め',
    meaning: 'Nhờ vả, yêu cầu',
    hanViet: 'LẠI',
    group: 1,
    endingBefore: 'み',
    rule: 'g1_mi_me',
  },

  // 9. Kết thúc り → れ
  {
    id: 'kaeru',
    kanji: '帰ります',
    hiragana: 'かえります',
    imperativeForm: 'かえれ',
    imperativeFormKanji: '帰れ',
    meaning: 'Về (nhà)',
    hanViet: 'QUY',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'tsukuru',
    kanji: '作ります',
    hiragana: 'つくります',
    imperativeForm: 'つくれ',
    imperativeFormKanji: '作れ',
    meaning: 'Làm, chế tạo',
    hanViet: 'TÁC',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'hashiru',
    kanji: '走ります',
    hiragana: 'はしります',
    imperativeForm: 'はしれ',
    imperativeFormKanji: '走れ',
    meaning: 'Chạy',
    hanViet: 'TẨU',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'toru',
    kanji: '取ります',
    hiragana: 'とります',
    imperativeForm: 'とれ',
    imperativeFormKanji: '取れ',
    meaning: 'Lấy, chụp',
    hanViet: 'THỦ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'hairu',
    kanji: '入ります',
    hiragana: 'はいります',
    imperativeForm: 'はいれ',
    imperativeFormKanji: '入れ',
    meaning: 'Đi vào',
    hanViet: 'NHẬP',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'shiru',
    kanji: '知ります',
    hiragana: 'しります',
    imperativeForm: 'しれ',
    imperativeFormKanji: '知れ',
    meaning: 'Biết',
    hanViet: 'TRI',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'ganbaru',
    kanji: '頑張ります',
    hiragana: 'がんばります',
    imperativeForm: 'がんばれ',
    imperativeFormKanji: '頑張れ',
    meaning: 'Cố lên',
    hanViet: 'NGOAN TRƯƠNG',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'suwaru',
    kanji: '座ります',
    hiragana: 'すわります',
    imperativeForm: 'すわれ',
    imperativeFormKanji: '座れ',
    meaning: 'Ngồi',
    hanViet: 'TỌA',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },
  {
    id: 'tomaru',
    kanji: '止まります',
    hiragana: 'とまります',
    imperativeForm: 'とまれ',
    imperativeFormKanji: '止まれ',
    meaning: 'Dừng lại',
    hanViet: 'CHỈ',
    group: 1,
    endingBefore: 'り',
    rule: 'g1_ri_re',
  },

  // ── NHÓM 2: Bỏ ます → Thêm ろ (一段動詞) ────────────────────
  {
    id: 'taberu',
    kanji: '食べます',
    hiragana: 'たべます',
    imperativeForm: 'たべろ',
    imperativeFormKanji: '食べろ',
    meaning: 'Ăn',
    hanViet: 'THỰC',
    group: 2,
    endingBefore: 'べ',
    rule: 'g2_ro',
  },
  {
    id: 'miru',
    kanji: '見ます',
    hiragana: 'みます',
    imperativeForm: 'みろ',
    imperativeFormKanji: '見ろ',
    meaning: 'Xem, nhìn',
    hanViet: 'KIẾN',
    group: 2,
    endingBefore: 'み',
    rule: 'g2_ro',
  },
  {
    id: 'neru',
    kanji: '寝ます',
    hiragana: 'ねます',
    imperativeForm: 'ねろ',
    imperativeFormKanji: '寝ろ',
    meaning: 'Ngủ',
    hanViet: 'TẨM',
    group: 2,
    endingBefore: 'ね',
    rule: 'g2_ro',
  },
  {
    id: 'okiru',
    kanji: '起きます',
    hiragana: 'おきます',
    imperativeForm: 'おきろ',
    imperativeFormKanji: '起きろ',
    meaning: 'Thức dậy',
    hanViet: 'KHỞI',
    group: 2,
    endingBefore: 'き',
    rule: 'g2_ro',
  },
  {
    id: 'akeru',
    kanji: '開けます',
    hiragana: 'あけます',
    imperativeForm: 'あけろ',
    imperativeFormKanji: '開けろ',
    meaning: 'Mở (cửa)',
    hanViet: 'KHAI',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_ro',
  },
  {
    id: 'shimeru',
    kanji: '閉めます',
    hiragana: 'しめます',
    imperativeForm: 'しめろ',
    imperativeFormKanji: '閉めろ',
    meaning: 'Đóng (cửa)',
    hanViet: 'BẾ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_ro',
  },
  {
    id: 'tomeru',
    kanji: '止めます',
    hiragana: 'とめます',
    imperativeForm: 'とめろ',
    imperativeFormKanji: '止めろ',
    meaning: 'Dừng lại, tắt',
    hanViet: 'CHỈ',
    group: 2,
    endingBefore: 'め',
    rule: 'g2_ro',
  },
  {
    id: 'oshieru',
    kanji: '教えます',
    hiragana: 'おしえます',
    imperativeForm: 'おしえろ',
    imperativeFormKanji: '教えろ',
    meaning: 'Dạy, chỉ bảo',
    hanViet: 'GIÁO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_ro',
  },
  {
    id: 'wasureru',
    kanji: '忘れます',
    hiragana: 'わすれます',
    imperativeForm: 'わすれろ',
    imperativeFormKanji: '忘れろ',
    meaning: 'Quên',
    hanViet: 'VONG',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_ro',
  },
  {
    id: 'tsuzukeru',
    kanji: '続けます',
    hiragana: 'つづけます',
    imperativeForm: 'つづけろ',
    imperativeFormKanji: '続けろ',
    meaning: 'Tiếp tục',
    hanViet: 'TỤC',
    group: 2,
    endingBefore: 'け',
    rule: 'g2_ro',
  },
  {
    id: 'kangaeru',
    kanji: '考えます',
    hiragana: 'かんがえます',
    imperativeForm: 'かんがえろ',
    imperativeFormKanji: '考えろ',
    meaning: 'Suy nghĩ',
    hanViet: 'KHẢO',
    group: 2,
    endingBefore: 'え',
    rule: 'g2_ro',
  },

  // ── NHÓM 3: Động từ bất quy tắc (不規則動詞) ─────────────────
  {
    id: 'suru',
    kanji: 'します',
    hiragana: 'します',
    imperativeForm: 'しろ',
    imperativeFormKanji: 'しろ',
    meaning: 'Làm',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'benkyousuru',
    kanji: '勉強します',
    hiragana: 'べんきょうします',
    imperativeForm: 'べんきょうしろ',
    imperativeFormKanji: '勉強しろ',
    meaning: 'Học tập',
    hanViet: 'MIỄN CƯỠNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'undousuru',
    kanji: '運動します',
    hiragana: 'うんどうします',
    imperativeForm: 'うんどうしろ',
    imperativeFormKanji: '運動しろ',
    meaning: 'Vận động, tập thể dục',
    hanViet: 'VẬN ĐỘNG',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'renshuusuru',
    kanji: '練習します',
    hiragana: 'れんしゅうします',
    imperativeForm: 'れんしゅうしろ',
    imperativeFormKanji: '練習しろ',
    meaning: 'Luyện tập',
    hanViet: 'LUYỆN TẬP',
    group: 3,
    endingBefore: 'し',
    rule: 'g3_suru',
  },
  {
    id: 'kuru',
    kanji: '来ます',
    hiragana: 'きます',
    imperativeForm: 'こい',
    imperativeFormKanji: '来い',
    meaning: 'Đến',
    hanViet: 'LAI',
    group: 3,
    endingBefore: 'き',
    rule: 'g3_kuru',
  },
  {
    id: 'kureru',
    kanji: 'くれます',
    hiragana: 'くれます',
    imperativeForm: 'くれ',
    imperativeFormKanji: 'くれ',
    meaning: 'Cho tôi (thể mệnh lệnh đặc biệt)',
    group: 2,
    endingBefore: 'れ',
    rule: 'g2_kure',
  },
];
